### ISSUE TITLE
Question about estimated Diff Expr parameters

### ISSUE THREAD

**Issue by kuang-da** [Oshlack/splatter#100]
Hi,

Thanks for such a great simulation tool. This is not an issue but more like a question because of my ignorance.

After estimating parameters from Tungs' data, the parameters about DE are as follows:
```
Diff expr: 
[Probability]    [Down Prob]     [Location]        [Scale] 
      0.1              0.5            0.1            0.4 
```
Based on the manual of Splatter, DE factors are sampled from a log-normal distribution where the mean and scale are 0.1 and 0.4. However, the expectation of such distribution is 1.197 and most of the time the DE factors are less than 1.5. 

I thought a 2-fold change in scRNA-seq data is already a relatively elusive signal. Therefore, I am a bit confused about such a parameter set-up.

Would you please introduce a little bit more about how to choose the DE parameter for a simulation to generally describe a single cell experiment if it would not take you too much time? Or any relative literature would be highly appreciated, thank you very much!

**Comment by lazappi** [comment]
Hi @kuang-da 

Thanks for giving **Splatter** a go! The DE parameters are not estimated from a real dataset (you should be able to see this marked when printing the parameters object).

The default parameters were chosen to be vaguely in the range of what is required to separate two groups on a dimensionality reduction plot but depending on other parameters this may not be the case. While most of the generated DE factors will be small a few large factors is enough to separate groups and is fairly similar to what is seen for many biological settings.

Choosing which DE parameters to use largely depends on the scenario you want to simulate. Do you want groups that are similar to each other or very different? In practice I usually play around with parameters until a t-SNE/UMAP looks like the scenario I am interested in.

**Comment by kuang-da** [comment]
Thanks for the explanation!
