### ISSUE TITLE
batch.rmEffect parameter

### ISSUE THREAD

**Issue by daynefiler** [Oshlack/splatter#102]
Hi, I am trying to get an old script to run where I would do a simulation with and without batch effects added in (keeping all other parameters the same):

    batchProb <- c(0.1714, 0.2, 0.0857, 0.0857, 0.4571)
    groupProb <- c(0.3703, 0.0223, 0.3197, 0.0051, 0.01, 0.0031, 
                   0.2031, 0.0057, 0.0551, 0.0056)
    
    p1 <- readRDS(file.path(wd, "estVeh.RDS"))
    p1 <- setParam(p1, "seed", seed)
    p1 <- setParam(p1, "batchCells", rmultinom(1, 2e4, batchProb)[ , 1])
    p1 <- setParam(p1, "group.prob", groupProb)
    p2 <- setParam(p1, "batch.rmEffect", TRUE)

Now, I am running into: `‘batch.rmEffect’ is not a slot in class “SplatParams”`. I cannot find anything online about that parameter, and I am unsure what version of `splatter` I was using. Was 'batch.rmEffect' a parameter previously? If so, how do I replicate the behavior using the current version?

**Comment by lazappi** [comment]
Hi @daynefiler 

I can't remember there ever being a `batch.rmEffect` parameter and a quick search of the git repository doesn't find any mentions of it. Is it possible you were using a modified version of **{Splatter}**? If you can find out which version you were using I might be able to have another look.

**Comment by daynefiler** [comment]
Hi @lazappi -- thank you for the quick reply. This is one of those face-palm moments. I did, indeed, fork & modify the package. I will send over a PR if you're interested. This is unrelated, but it would be very cool to add an extra "batch" step to the algorithm, allowing for adding treatment effects. If you're interested, I can open another issue and we can discuss how to best implement. Thanks, again!

**Comment by lazappi** [comment]
I think we can close this now and continue the discussion on #103. Reopen if you there's something outside the PR you want to discuss here.
