### ISSUE TITLE
Replacement for akima::aspline()?

### ISSUE THREAD

**Issue by evanbiederstedt** [Oshlack/splatter#108]
Hi there

Thank you for the excellent work!

We're using splatter as a dependency in a package we are trying to submit to CRAN. 

Unfortunately, there's a function causing some licensing issues here:

https://github.com/Oshlack/splatter/blob/master/R/splat-simulate.R#L910

`akima` has been on CRAN for over 20 years, but it has licensing issues which cause problems for packages which us this as a dependency. In fact, the creators tried to write another package to get around these ACM licensing issues, https://cran.r-project.org/web/packages/interp/index.html

See this poster from the authors as well [bivand_gebhardt_user17_a0.pdf](https://github.com/Oshlack/splatter/files/5606679/bivand_gebhardt_user17_a0.pdf)

Are there any alternatives you could use as opposed to `akima::aspline()`? That could save us some headache. 

I took a look at the original function with the goal of making a pull request to splatter, but the original Fortran code looks a bit hairy: https://github.com/cran/akima/blob/master/R/aspline.R

Any help appreciated. Thank you, Evan 

CC @lazappi @aliciaoshlack

**Comment by evanbiederstedt** [comment]
Not only is the Fortran code a bit tricky to deal with, it have the same licensing issues which plague the package akima. 

This appears to be the only time in splatter which an akima function is used. Could we replace akima::aspline() with another univariate interpolation method? Maybe something this? https://rdrr.io/cran/McSpatial/man/smooth12.html

Please let me know your thoughts. To re-emphasize, the reason we're so interested in this is that we would like to submit a package on CRAN with splatter as a dependency, and the akima license causes us a few problems...

Thank you and let me know how to help out---I'm happy to implement something if we agree on a direction forward. 

Best, Evan

**Comment by lazappi** [comment]
Hi @evanbiederstedt 

Thanks for raising this as an issue, I wasn't aware of it before. I was under the general impression that licenses applied when borrowing code but not when depending on a package. Pretty sure that is true for common open-source licenses but maybe not in this case. Could you maybe explain in a little more detail what the licensing issue is and which part affects you/Splatter?

It does seem to be an issue though so I am happy to consider alternatives. As you mentioned this is only used for one small part of the Splat simulation. If there is another minimal dependency or a function we can borrow that would be ideal. Would just need to do some comparisons to check the results are similar but that should be fairly straightforward.

**Comment by 4lge** [comment]
Hi all,

I'm the maintainer of the akima package. 

The problem with Akimas Fortran code is that it is ACM licensed, which only allows non-commercial reuse. This applies to many other code packages from netlib from the seventies as the authors had to transfer their rights on their code to get their articles published.

Some  but not all parts of the akima and tripack package are reimplemented in the interp package. The 2d interpolation is still not working, the 1d interpolation was not on my agenda. So if you find something useable in other packages I would suggest to use this.

Maybe stats::spline() works?

Best,

Albrecht

**Comment by evanbiederstedt** [comment]
Thank you for the help, @4lge 

> Could you maybe explain in a little more detail what the licensing issue is and which part affects you/Splatter?

To add more information on this front, when submitting my package to CRAN, there are automatic checks which CRAN runs. It detected there was a licensing problem with my package, i.e. 

```
Package has a FOSS license but eventually depends on the following
package which restricts use:
  akima
```

I tracked down that this was due to using a function from `splatter` and importing `splatter` in the DESCRIPTION file. Amusingly, all of this trouble only appears to be due to that single function call, which is a good thing---we should be able to replace it quickly enough. 

Let me know if I could help out on this. As I say, I was originally going to create a pull request to replace that function. Perhaps `stats::spline()` would work, as Albrecht mentioned?

Thank you, Evan

**Comment by lazappi** [comment]
Thanks for the info @4lge and @evanbiederstedt 

Possibly Bioconductor doesn't run these licensing checks which is why this hasn't come up before.

Only a very quick check but it looks like a natural spline from `stats::spline(..., method = "natural")` should be a reasonable substitute:

```r
library(tidyverse)

BB <- c(0, 3.2, 5.2, 4.6, 5)

df <- data.frame(
    Step     = 1:100,
    Akima    = akima::aspline(BB, n = 100)$y,
    FMM      = stats::spline(BB, n = 100, method = "fmm")$y,
    Periodic = stats::spline(BB, n = 100, method = "periodic")$y,
    Natural  = stats::spline(BB, n = 100, method = "natural")$y
)

df %>%
    pivot_longer(cols = -Step) %>%
    ggplot(aes(x = Step, y = value, colour = name)) +
    geom_point() +
    geom_point(
        data = data.frame(Step = seq(0, 100, 25), value = BB),
        colour = "black", size = 5, shape = 4
    )
```

![image](https://user-images.githubusercontent.com/6869320/100547401-cea67300-3266-11eb-9df9-453d2d556b7c.png)

Must not have known about this otherwise I probably would have done that to start with.

@evanbiederstedt If you are able to submit a PR that would be great, otherwise I can hopefully get to it this week. Short checklist for whoever does look at it:

- [ ] Replace `akima::aspline()` with `stats::spline(..., method = "natural")`
- [ ] Remove the **akima** dependency
- [ ] Check for mentions of Akima in documentation (and replace)
- [ ] Run checks and tests (locally and CI)

**Comment by evanbiederstedt** [comment]
Hi @lazappi 

Thank you for the help with this. I have a PR here: https://github.com/Oshlack/splatter/pull/109

I think I have taken out any mention of `akima`, but I could have missed something of course. 

Naturally, this also will need to be updated on Bioconductor to make the CRAN errors stop entirely. 

I appreciate the quick help on this front; please let me know if there is anything else I could do. 

Best, Evan

**Comment by lazappi** [comment]
PR has been pushed to Bioconductor and should be available from there in the next couple of days.

**Comment by evanbiederstedt** [comment]
Thanks @lazappi!

**Comment by lazappi** [comment]
Versions 1.14.1 (release) and 1.15.1 (devel) are now available from Bioconductor and should be installed when using `BiocManager::install()`.

**Comment by evanbiederstedt** [comment]
I appreciate the help, @lazappi---especially how timely this all was. 

I think this should resolve the issue here! Thank you!
