### ISSUE TITLE
Can we estimate parameters for a dataset with labels?

### ISSUE THREAD

**Issue by faro1219** [Oshlack/splatter#111]
I am trying to estimate parameters for a dataset cortex. Now I already know how to estimate the parameters without the information of labels. But I am wondering if we could use Splatter to estimate parameters for different groups and simulate data will labels?

**Comment by lazappi** [comment]
Hi @faro1219 

Thanks for giving **Splatter** a go! As you have already noticed the `splatEstimate()` function doesn't know anything about groups in the data and estimates global parameters. Currently there is no way to estimate group-specific parameters for Splat. Some of the other models in **Splatter** (or alternative packages) may this feature.

Sorry I can't be more help.
