### ISSUE TITLE
Simulate several two-group(condition) cell types with specified number (proportion) of overlapping DE genes

### ISSUE THREAD

**Issue by KANG-BIOINFO** [Oshlack/splatter#115]
Hi @lazappi , Thanks so much for you fantastic package. I like it a lot.
I'm trying to simulate several cell types, with two groups (condition, e.g. control vs. perturbed) in each cell type. How can I simulate required proportion (number) of overlapping DE genes for control_vs_perturbed across different cell types.

```
### simulation 1
sim = splatSimulateGroups(params, 
                          group.prob = c(0.5, 0.5),
                          de.prob = c(0.2, 0.2),
                          de.downProb = c(0.2, 0.2),
                          )

gene_meta = rowData(sim)
group1_up_sim1 = rownames(gene_meta[gene_meta$DEFacGroup1 > gene_meta$DEFacGroup2,])
group2_up_sim1 = rownames(gene_meta[gene_meta$DEFacGroup1 < gene_meta$DEFacGroup2,])

### simulation 2
params = setParam(params, "seed", 162790)
sim2 = splatSimulateGroups(params, 
                          group.prob = c(0.5, 0.5),
                          de.prob = c(0.2, 0.2),
                          de.downProb = c(0.2, 0.2),
                          )
gene_meta2 = rowData(sim2)
group1_up_sim2 = rownames(gene_meta2[gene_meta2$DEFacGroup1 > gene_meta2$DEFacGroup2,])
group2_up_sim2 = rownames(gene_meta2[gene_meta2$DEFacGroup1 < gene_meta2$DEFacGroup2,])

### overlapping of DE genes of each group across two simulations (can't control the number of overlapping genes across simulations)
group1_up_overlap = intersect(group1_up_sim1, group1_up_sim2)
group2_up_overlap = intersect(group2_up_sim1, group2_up_sim2)
```

Here's an example I have. I had two simulations, with 2 groups in each one. I set 20% of DE genes in each group. It seems DE genes were randomly assigned in each simulation, so I can't control how many DE genes (in either group 1 or group 2) are overlapping across simulations. Is there a way I can control the number of overlapping DE genes in multiple simulations? 

Thanks so much!

**Comment by lazappi** [comment]
Hi @KANG-BIOINFO 

Thanks for giving Splatter a go 🎉! Currently each Splat simulation is completely independent so there is no way to make sure that genes from one simulation match up with genes from another simulation. This is a hangover from a simpler time before people were interested in more complex experiments and is something I plan to address in upcoming updates, but there is no timeline for those yet.

For now there might be a few options you could try. If you are interested in having replicates of the same experiment you could try using the batch effect settings in Splat. Another more manual option is to use Splat to generate a base dataset and modify that in some way to get what you want. It is also probably worth looking at other simulation models (is Splatter or other packages) to see if they can do what you are looking for.

Hope that helps, happy to answer further questions.

**Comment by lazappi** [comment]
Closing this issue now but reopen if you have follow up questions.
