### ISSUE TITLE
"TrueCounts" identical to "counts"

### ISSUE THREAD

**Issue by alexandruioanvoda** [Oshlack/splatter#116]
Hi! Great paper and package! Thank you for developing/maintaining this.

The example from the vignette, with set seed for reproducibility if needed:

```
set.seed(1)
suppressPackageStartupMessages({
  library(splatter)
  library(scater)
})
sce <- mockSCE()
params <- splatEstimate(sce)
sim <- splatSimulate(params)
```
Then, running `all(sim@assays@data@listData[["TrueCounts"]] == sim@assays@data@listData[["counts"]])` gives `TRUE`

Is this the intended result for the vignette example dataset, for the counts to have no drop-out?

**Comment by lazappi** [comment]
Hi @alexandruioanvoda

Thanks for giving **{splatter}** a go! By default dropout is turned off for the Splat simulation so the `TrueCounts` assay will equal counts. To turn dropout on you need to set the `dropout.type` parameter, for example:

```r
sce <- mockSCE()
params <- splatEstimate(sce)
sim <- splatSimulate(params, dropout.type = "experiment")
```
