### ISSUE TITLE
splatPop finding eQTL locations

### ISSUE THREAD

**Issue by ceesu** [Oshlack/splatter#119]
Hello again, 
I'd like to simulate two populations with some significant difference in specific genes. Within SplatPop, to my understanding this can done by controlling the eqtl parameters. However, if I simulate populations as follows:
```
params <- newSplatPopParams()
params <-setParams(params,eqtl.n=2)
vcf <- mockVCF(n.samples = 2)
splat_sim = splatter::splatPopSimulate(params, vcf = vcf,
                                          verbose = FALSE)
splat_sim<- logNormCounts(splat_sim)
splat_sim <- runPCA(splat_sim)
plotPCA(splat_sim, colour_by = "Sample")
```

I can see two samples in the PCA, which is what I specified in vcf. However, I also specified 2 eqtls in params. Is it possible to figure out which genes those eqtls landed within and the associated effect sizes?

**Comment by lazappi** [comment]
Ping @azodichr
