### ISSUE TITLE
How to use Kersplat?

### ISSUE THREAD

**Issue by aradley** [Oshlack/splatter#121]
Hi,

Hope you're well.

I was wondering if you would be able to shed some light on how to use the Kersplat simulation method please?

I'm definitely interested in creating a synthetic data set with cells transitioning between "cell types" based on some underlying GRNs. Unfortunately I can't seem to find any clear description of how to try this with Kersplat. Do you have some example code, or better, example code + input parameters/GRNs that I could try please?

Best,

Arthur

**Comment by lazappi** [comment]
Hi @aradley. I'm not sure what you have looked at already but there is documentation for the various Kersplat simulation functions (`?KersplatParams`, `kersplatSimulate`, `?kersplatSetup`, `?kersplatSample`). These should help with the details but in general they work in a similar way to the Splat functions. If there is something more specific you are interested in happy to help out more.

I would add that Kersplat is still experimental and has some fairly big flaws, particularly around parts of the gene network. If a network-based simulation is what you need I would suggest having a look at some of the other packages out there, [dyngen](https://github.com/dynverse/dyngen) or [PROSSTT](https://github.com/soedinglab/prosstt) for example.

**Comment by aradley** [comment]
Thank you very much for your reply, this is very helpful.

I will look at the kersplat function info's, but dyngen also looks very much like what I'm looking for, so thank you for pointing me towards it.

Best,

Arthur
