### ISSUE TITLE
Error when simulating more samples with splatPop

### ISSUE THREAD

**Issue by wanghao98** [Oshlack/splatter#125]
Hi, in the tutorial, samples = 5 was used to simulate data. When I tried to increase sample size to more than 20, I had the following error:

`Error in sample.int(length(x), size, replace, prob) : 
  invalid first argument`

Here is the Code I used:

```r
vcf = mockVCF(n.sample = 40)
gff <- mockGFF()

params.cond <- newSplatPopParams(eqtl.n = 0.5, 
                                 batchCells = 100,
                                 similarity.scale = 5,
                                 condition.prob = c(0.5, 0.5),
                                 eqtl.condition.specific = 0.5,
                                 cde.facLoc = c(0.5, 0.5), 
                                 cde.facScale = c(0.5, 0.5))
sim.pop.cond <- splatPopSimulate(vcf = vcf, gff = gff, params = params.cond, 
                                 sparsify = FALSE)
```

Thank you for looking into this!

**Comment by lazappi** [comment]
@wanghao98 This should be fixed now and will be in the current Bioconductor release (3.14) and devel (3.15) soon. If you haven't updated to the new Bioconductor version yet you can install it from GitHub.
