### ISSUE TITLE
Parameters when simulating path

### ISSUE THREAD

**Issue by kevin199011** [Oshlack/splatter#13]
Hi, when I run sim.paths <- splatSimulate(method = "paths", verbose = FALSE), with default parameters, the 1st and 2nd PC components only explained 4% and 2%. I was wondering what parameters should be responsible to get similar result as in the vignettes, which has 29% variance in 1st component?

P.S. My R is 3.3.2 and the splatter is 0.99.0. Does it have something to do with the splatter version?

Thank you!

Kevin

**Comment by lazappi** [comment]
Hi Kevin

Thanks for giving Splatter a go. I have modified the default parameters in more recent versions of Splatter that are used to make the vignette on the Bioconductor website which could explain the difference in the results. It could also be the particular simulation, try changing the `seed` parameter and see if that produces a different result. It might also be worth looking at a PCA of some real data and seeing how much variance those components explain. 

I hope that helps, let me know if you have any other questions.

Luke

P.S. Default parameters in the most recent version.

```
A Params object of class SplatParams 
Parameters can be (estimable) or [not estimable], 'Default' or 'NOT DEFAULT'. 

Global: 
(Genes)  (Cells)   [Seed]  
  10000      100   526662  

23 additional parameters 

Groups: 
     [Groups]  [Group Cells]  
            1            100  

Mean: 
 (Rate)  (Shape)  
    0.3      0.6  

Library size: 
(Location)     (Scale)  
        11         0.2  

Exprs outliers: 
(Probability)     (Location)        (Scale)  
         0.05              4            0.5  

Diff expr: 
[Probability]    [Down Prob]     [Location]        [Scale]  
          0.1            0.5              4              1  

BCV: 
(Common Disp)          (DoF)  
          0.1             60  

Dropout: 
 (Present)  (Midpoint)     (Shape)  
     FALSE           0          -1  

Paths: 
        [From]        [Length]          [Skew]    [Non-linear]  [Sigma Factor]  
             0             100             0.5             0.1             0.8  
```

**Comment by kevin199011** [comment]
Hi Luke, thank you so much for the explanation. After changing to the new parameters, the PCA plot looks as in the vignette. Also I realized that the Dropout True/False makes a big difference.

Another question I have is about the Differential expression. I'm not sure how this was determined. I'm wondering for example, when I'm setting the probability as 0.1. Does this mean 10% of total genes are simulated as differential expressed genes? If so, is it possible to know what genes are simulated as DEGs?

Thank you!

Kevin

**Comment by lazappi** [comment]
Hi Kevin

I'm glad that helped. Yes, dropout can make a big difference, it depends on what kind of data you are trying to simulate.

Yes, setting `de.prob = 0.1` will make 10% of genes differentially expressed. To find out which genes are DE have a look at the `DEFactor` columns in `fData(your_sim)`. Values different from 1 indicate that a gene is DE in a particular group/path.

Luke

**Comment by lazappi** [comment]
It seems that we have sorted out your issues so I am going to close this issue. Please contact me again if you have more questions.
