### ISSUE TITLE
computeSumFactors function in scran package was moved to scuttle package

### ISSUE THREAD

**Issue by duohongrui** [Oshlack/splatter#130]
Hi,
When I used the Lun2 algorithm in Splatter to estimate the parameters from a real dataset, the error always occurred like this: 
```
sce <- mockSCE()
plates <- as.numeric(factor(colData(sce)$Mutation_Status))
params <- lun2Estimate(sce, plates, min.size = 20)
```
```
Estimating number of groups...
Computing normalisation factors...
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘assay’ for signature ‘"matrix", "character"’
```
I investigated the source of this error and found the reason why the error happened. The source codes of computing normalization factors in lun2Estimate function are `scran::computeSumFactors`, but the `computeSumFactors` function in **scran** was moved to **scuttle** package according to the descriptions of the reference manual of scran package in Bioconductor.
Then I changed the `scran::computeSumFactors` to `scuttle::pooledSizeFactors` within the source codes and retried, and the error was solved.

Could you check the functions and compatibility between these two packages? Thanks a lot!

**Comment by lazappi** [comment]
Hi @duohongrui

Thanks for giving Splatter a go and reporting the error! I think you are probably right but if you could let me know what versions of **R**, **{splatter}**, **{scran}** and **{scuttle}** you are using that would be helpful. Something like this would be great:

```r
library(splatter)
library(scran)
library(scuttle)

sessionInfo()
```

**Comment by duohongrui** [comment]
Here they are:
```
R version 4.1.1 (2021-08-10)
splatter 1.16.1
scran 1.20.1
scuttle 1.2.1
```
Thanks very much!

**Comment by lazappi** [comment]
Thanks again for the bug report @duohongrui. I have made the fix in devel and release and it should be available from Bioconductor in the next few days.
