### ISSUE TITLE
Finding marker genes in eah group

### ISSUE THREAD

**Issue by emkahuda** [Oshlack/splatter#136]
I have been using splatter to generate scRNA synthetic data. However, when I used the generated synthetic data for the Seurat object, I found some clusters do not have a single marker gene (or sometimes they have but only a few). Is there any way that I can find marker genes for each group or cluster then add them to the metadata?

**Comment by lazappi** [comment]
Hi @emkahuda 

Thanks for giving **{splatter}** a go! Please have a look at this issue for information on how to find the ground truth simulated DE genes https://github.com/Oshlack/splatter/issues/57. I will also point out that all the simulated DE genes may not be detected by the marker gene test depending on the foldchanges etc.

**Comment by emkahuda** [comment]
Hi, thank you for the reply. So, actually what I am looking for are  
1. How can we know which cells belong to which cell types (which cluster or group)? 
2. Then, after knowing a list of cells in each group, I am wondering if then we can find the list of marker genes of each group? 
I cannot find the clustering algorithm in splatter. What I understand, we can set what kind of synthetic data we want such as how many group or clusters and the size of those groups, including to set the probability of genes to be DE genes. Could you please help? I might have missed something

**Comment by emkahuda** [comment]
I see. Thank you very much for the information.  I will check it out.

Best regards,

Huda

**Comment by emkahuda** [comment]
Dear Luke Zappia,

I hope you stay safe and healthy. I have been trying to understand how Splatter generates synthetic data. I know it does not perform clustering, to begin with. However, when we set the parameter to have a specific number of genes and a specific number of cells, as well as the number of groups (clusters?) for the simulation, I am wondering how are cells assigned to which group when the splatter generates synthetic data? Are the cells randomly chosen and assigned to a group? Or it depends on the package SC3 (and let the SC3 packages do the grouping)?

Thank you very much for your help. 

Best regards,

Huda

**Comment by lazappi** [comment]
During the simulation process cells are randomly assigned to groups (with numbers depending on the `group.prob` parameter). You can consider these "Group" labels as the ground truth identity for each cell which you could compare to the clusters from whatever clustering method such as SC3. There is no direct relationship between **{splatter}** and any downstream analysis method.

**Comment by emkahuda** [comment]
Dear Luke Zappia,

Thank you for the clarification email about the cluster (groups). I am trying to generate synthetic data (scRNA-seq Glioblastoma dataset) using Splatter, but the clusters obtained of the synthetic data result is somehow really different from the real data clusters. Both clusters are obtained by the Seurat clustering algorithm. Please see the UMAP plots for both datasets. I also attached the file in which I produce the synthetic data. Could you please have a look, in case I made a mistake in a step generating the synthetic data. 

In general, what I have done to produce the synthetic data are;
1. Load the real data (scRNA_seq Glioblastoma)
2. Create a Seurat object for this loaded data
3. Do the quality control (such as only including counts with the minimum cell are 3 and minimum gene is 350)
4. Clusters the cells using the Seurat algorithm
5. Plot the UMAP for these clusters
6. Getting the matrix counts 
7. Use this matrix as the input for SplateSimulate() function to obtain the synthetic data
8. Set the number of groups I want (10 groups),  the size of each group (randomly assigning the prob. for each size), and the DE prob by 0.3.
9. I repeat steps 2-5 to obtain new clusters for the synthetic data. 
10. compare the UMAP Plots (Here I found the two UMAP Plots show the clusters of real data and synthetic data are significantly different). 

Could you please help why this is the case? Thank you very much.

Best regards,

Huda

**Comment by lazappi** [comment]
I can't see the uploaded files (I think you need to attach them on GitHub, not by email) but this is not unexpected. The parameters for creating groups are not estimated directly from a real dataset and it would take some adjusting to get them to match. For example,  I think you have randomly set `group.prob` but this would need to match the proportions in the real dataset (it's a bit hard to tell without any code). You may be able to get something that looks very close to your example dataset but it's non-trivial.

I would consider why you want to have an exact replica of a real dataset? The strength of simulations is being able to test scenarios for which there is no real data. If you already have this data I would suggest using it directly rather than trying to create a simulated copy of it. If there is a reason that won't work think about what scenario you want to simulate rather than just recreating a real dataset.

**Comment by emkahuda** [comment]
Dear Luke,


I see. I misunderstood of the parameter estimation process in this case.


Yes, these points you mentioned do make sense.  I was thinking to recreate (mimic) the real dataset to check whether the classification methods I make work properly if both result show high similarities. However,  as you mentioned,  I can actually do both separately and use them for analysis.

Thank you very much for the explanation.


Best regards,

Huda

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
