### ISSUE TITLE
Annotating simulated genes as differentially expressed or not

### ISSUE THREAD

**Issue by dinithins** [Oshlack/splatter#137]
Hi, I am using Splatter to simulate differential expression for 2 groups. I want to label each gene in the simulated dataset as a true positive of DE or true negative of DE. As the documentation says that "DEFacGroup<id>" having a value of 1 indicates that a gene is not DE, I extracted the genes for which **DEFacGroup<id> is not equal to 1** for both groups, separately, so that I have a true DE gene list across both groups by taking the union of the above 2 separate extractions. Then I notice that there are several genes that appear differentially expressed in terms of both groups. Since we consider a gene to be DE with respect to one another, how should those few genes be interpreted as DE or non DE? May be I am missing something here, and I greatly appreciate if the identificaiton of a true DE gene can be clarified. Thanks in advance!

Below is the code snippet I am running. 

```r
params <- newSplatParams()

params <- setParam(params, "nGenes", 1000) 
params <- setParam(params, "batchCells", 1000) 
params <- setParam(params, "group.prob", c(0.5,0.5)) 
params <- setParam(params, "de.prob", 0.03) 
params <- setParam(params, "de.facLoc", 0.7 )
params <- setParam(params, "de.facScale", 1.0) 
params <- setParam(params, "dropout.type", "experiment") 
params <- setParam(params, "dropout.mid", 0 )
params <- setParam(params, "dropout.shape", -1)

sim <- splatSimulate(params, method="groups", verbose=FALSE)
```

**Comment by lazappi** [comment]
Hi @dinithins 

Thanks for giving **{splatter}** a go! Please have a look at the comments in  https://github.com/Oshlack/splatter/issues/57. Hopefully that will answer your question but please reply if anything isn't clear.

**Comment by dinithins** [comment]
Many thanks! The detailed explanation in #57 is very clear and answers my question.
