### ISSUE TITLE
Is it possible to set the exact number of cells belonging to a group?

### ISSUE THREAD

**Issue by inoue0426** [Oshlack/splatter#143]
Hi

I would like to generate single-cell RNA data belonging to two groups. In this case, the probability of belonging to each group is c(0.5, 0.5), so for 1000 data points, we would like 500 data points to belong to each group, but this is slightly off. Is there something wrong with my settings? Or is this just the way it is supposed to be?

```R
> set.seed(1)
> 
> sim.groups <-  splatSimulate(
+   nGenes = 1000, batchCells = 1000,
+   group.prob = c(0.5, 0.5), method = "groups"
+ )
Getting parameters...
Creating simulation object...
Simulating library sizes...
Simulating gene means...
Simulating group DE...
Simulating cell means...
Simulating BCV...
Simulating counts...
Simulating dropout (if needed)...
Sparsifying assays...
Automatically converting to sparse matrices, threshold = 0.95
Skipping 'BatchCellMeans': estimated sparse size 1.5 * dense matrix
Skipping 'BaseCellMeans': estimated sparse size 1.5 * dense matrix
Skipping 'BCV': estimated sparse size 1.5 * dense matrix
Skipping 'CellMeans': estimated sparse size 1.5 * dense matrix
Skipping 'TrueCounts': estimated sparse size 2.51 * dense matrix
Skipping 'counts': estimated sparse size 2.51 * dense matrix
Done!
> 
> sum(colData(sim.groups)$Group == 'Group1')
[1] 493
> sum(colData(sim.groups)$Group == 'Group2')
[1] 507
> 
```

The function with ` batchCells = c(500, 500)` is re-produce the same result.

```R
> sim.groups <-  splatSimulate(
+   nGenes = 1000, batchCells = c(500, 500),
+   group.prob = c(0.5, 0.5), method = "groups"
+ )
Getting parameters...
Creating simulation object...
Simulating library sizes...
Simulating gene means...
Simulating batch effects...
Simulating group DE...
Simulating cell means...
Simulating BCV...
Simulating counts...
Simulating dropout (if needed)...
Sparsifying assays...
Automatically converting to sparse matrices, threshold = 0.95
Skipping 'BatchCellMeans': estimated sparse size 1.5 * dense matrix
Skipping 'BaseCellMeans': estimated sparse size 1.5 * dense matrix
Skipping 'BCV': estimated sparse size 1.5 * dense matrix
Skipping 'CellMeans': estimated sparse size 1.5 * dense matrix
Skipping 'TrueCounts': estimated sparse size 2.51 * dense matrix
Skipping 'counts': estimated sparse size 2.51 * dense matrix
Done!
> sum(colData(sim.groups)$Group == 'Group1')
[1] 493
> sum(colData(sim.groups)$Group == 'Group2')
[1] 507
> 
```

**Comment by lazappi** [comment]
Hi @inoue0426 

As suggested by the name the `cell.prob` parameter contains probabilities rather than exact proportions. For this reason you would expect to get ~50% of cells in each group but not exactly 500. Currently there is no option to set exact numbers with the Splat simulation.

**Comment by inoue0426** [comment]
Hi @lazappi 

I see. May I make a Pull Request for developing such an option in the future?
Though not sure this is important for the other users to develop 🤔

**Comment by lazappi** [comment]
I am happy to discuss it. You would need to argue 1) why this is needed and 2) how it would work within the current framework.

**Comment by inoue0426** [comment]
@lazappi 

1) I thought that people who use group methods want to try to use their methods to evaluate scRNA imputation or machine learning models. So, the distribution of samples should be the same among classes although the number of data points belonging to each class may not have to be exactly the same 🤔 

2) Personally, I would like to make it so that if we put c(500, 500) as a parameter, we can get exact the number of data points.

But yeah I'm still studying this field and may perspective may not be what users want though...

**Comment by lazappi** [comment]
> 1. I thought that people who use group methods want to try to use their methods to evaluate scRNA imputation or machine learning models. So, the distribution of samples should be the same among classes although the number of data points belonging to each class may not have to be exactly the same 🤔

You will never get balanced classes in a real dataset so I think you should actually avoid this in any simulation you are using to develop methods/models.

> 2. Personally, I would like to make it so that if we put c(500, 500) as a parameter, we can get exact the number of data points.

Yeah, I can see that some people would prefer that. Very early versions of the Splat model did work this way but we changed it to be a probability to fit in with the rest of the model which is probabilistic. It probably wouldn't be too hard to add a parameter to change this behaviour if there was a good enough reason to. Another way to get exact numbers would be to generate slightly more cells than you want (say 1100 in your example) and then subsample cells to get the number you want (500 of each class).

**Comment by inoue0426** [comment]
> You will never get balanced classes in a real dataset so I think you should actually avoid this in any simulation you are using to develop methods/models.

Ah, yeah I understand.

> Yeah, I can see that some people would prefer that. Very early versions of the Splat model did work this way but we changed it to be a probability to fit in with the rest of the model which is probabilistic. It probably wouldn't be too hard to add a parameter to change this behaviour if there was a good enough reason to. Another way to get exact numbers would be to generate slightly more cells than you want (say 1100 in your example) and then subsample cells to get the number you want (500 of each class).

Yes, I think so. I also tried to do subsampling from the data.
Actually, it's enough and yeah the library may not need to implement the other function like that.

**Comment by lazappi** [comment]
I'm going to close this now but please comment if you have further questions.
