### ISSUE TITLE
The "Row.names" column is different with the rownames of the RowData in SplatPop result

### ISSUE THREAD

**Issue by duohongrui** [Oshlack/splatter#149]
Hi, SplatPop is a powerful method to simulate different groups. But these days I met some hard problems when I was using it. The reference dataset I used was downloaded from [GEO54695](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE54695). After estimating the parameters of this dataset, I met some problems.
**Question1:** The "Row.names" column is different with the rownames of the RowData in SplatPop result.
Here is the codes for preprocessing the reference data.
```
## Download data
download.file(url = "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE54695&format=file&file=GSE54695%5Fdata%5Ftranscript%5Fcounts%2Etxt%2Egz",
              destfile = "./data-raw/GSE54695_data_transcript_counts.txt.gz",
              method = "auto")
## Read data
data <- read.table("./data-raw/GSE54695_data_transcript_counts.txt.gz",
                   header = T,
                   row.names = 1)
## Filter
data <- data[, c(1:80, 161:240)]
## ERCC counts
ERCC_data <- data[grep(rownames(data), pattern = "^ERCC-"), ]
## Delete ERCC counts
data <- data[-grep(rownames(data), pattern = "^ERCC-"), ]
## Sample extra 3950 genes
data <- data[rowSums(data) > 200, ]
data <- data[sample(1:nrow(data), 3950), ]
## rbind
data <- as.matrix(round(rbind(data, ERCC_data)))
```
```
parameters<- splatter::splatPopEstimate(data,
                                        means = NULL,
                                        eqtl = NULL)
simulate_result <- splatter::splatPopSimulate(parameters,
                                              method = "groups",
                                              prob.group = c(0.4, 0.6),
                                              vcf = splatter::mockVCF(n.samples = 1, seed = 111),
                                              gff = splatter::mockGFF(n.genes = ncol(data), seed = 111),
                                              eqtl = NULL,
                                              means = NULL,
                                              key = NULL,
                                              verbose = TRUE)
row_data <- as.data.frame(rowData(simulate_result))
View(row_data)
```
![image](https://user-images.githubusercontent.com/68155800/179437055-4710607a-8c04-4c9f-9d7b-1ec6829f2124.png)
Note that the "Row.names" column is different with the rownames of the RowData in SplatPop result. Which is correct ?
**Question2:** SplatPop is not able to simulate different batches as it dose not finish the simulation step for over 10 hours.
When I used the same learned parameters to simulate two batches, I did not finish the step for over 10 hours.
```
simulate_result <- splatter::splatPopSimulate(parameters,
                                              method = "groups",
                                              prob.group = c(0.4, 0.6),
                                              batchCells = c(80, 80),
                                              vcf = splatter::mockVCF(n.samples = 1, seed = 111),
                                              gff = splatter::mockGFF(n.genes = ncol(data), seed = 111),
                                              eqtl = NULL,
                                              means = NULL,
                                              key = NULL,
                                              verbose = TRUE)
Designing population...
Simulating data for genes in GFF...
Simulating gene means for population...
```
And it processed until `Simulating gene means for population...` returned.
To further find out why this would happen, I followed the instructions of SplatPop in Bioconductor and everything was OK. I was confused about it because I usually use splatter package to simulate datasets and I can sure that all codes are OK.
Could you help me solve the problems? Thanks very much!

**Comment by azodichr** [comment]
@duohongrui we are happy to hear you like the splatter software and thanks for giving splatPop a try.

Q1:  Thanks for reporting this problem to us! The correct gene ids are the ones in “Row.names”, not rownames! I have identified the source of this error and fixed it (@lazappi see pull issue_149 request). Once this fix is incorporated into the GitHub repo you can use the dev version (`devtools::install_github(“Oshlack/splatter”)`) and we will include this fix in the next bioconductor release. 

Q2: This is happening because splatPop is trying to assign 10 samples to each batch (default `batch.size=10`), but only 1 sample is being provided (mockVCF `n.samples=1`). Having the code hang in this situation is certainly not what we want! The quick fix for you is to either add `batch.size=1` to your splatPopSimulate call or to simulate data for >10 samples. @lazappi I have added a patch to check if the batch.size param is > nSamples and to print a message and set batch.size=-nSamples in this case. 

Please let us know if you have more issues with the software.

**Comment by duohongrui** [comment]
Thanks for patient responses. I have already changed my simulation codes and everything was OK in SplatPop.
But just today, I wanted to simulation datasets with ERCC spike-in information, so I chose BASiCS simulation framework in Splatter package but there is a bug in BASiCS-simulate.R.
Here are my codes:
```
library(scater)
set.seed(1)
sce <- mockSCE()
spike.info <- data.frame(Name = rownames(sce)[1:10],
                         Input = rnorm(10, 500, 200),
                         stringsAsFactors = FALSE)
params <- splatter::BASiCSEstimate(sce[1:100, 1:30], spike.info)
simulation_result <- splatter::BASiCSSimulate(params, verbose = TRUE)

Error in checkSlotAssignment(object, name, value) : 
‘spike.mu’ is not a slot in “BASiCSParams” class
```
The original source of this error exists in BASiCS-simulate.R and the codes are here:  **params <- setParam(params, "spike.mu", spike.mu)**. But there is no slot named **spike.mu** in AllClasses.R.
![image](https://user-images.githubusercontent.com/68155800/180728236-13964ff0-dda8-4443-83d3-748124d2abe6.png)
Environment:
```
other attached packages:
 [1] splatter_1.21.0             SingleCellExperiment_1.18.0 SummarizedExperiment_1.26.1
 [4] Biobase_2.56.0              GenomicRanges_1.48.0        GenomeInfoDb_1.32.2        
 [7] IRanges_2.30.0              S4Vectors_0.34.0            BiocGenerics_0.42.0        
[10] MatrixGenerics_1.8.0        matrixStats_0.62.0
```
I am very sorry for disturbing you so many times, but some functionalities in certain method frameworks are very helpful and useful.
Thanks again for solving this problem!

**Comment by lazappi** [comment]
@duohongrui I have moved discussion about the BASiCS issue to #153
