### ISSUE TITLE
Clustering analysis on simulated data

### ISSUE THREAD

**Issue by DongzeHE** [Oshlack/splatter#150]
Hello,

Thank you so much for providing such an excellent tool to the single-cell community!

Recently I have been exploring the clustering algorithms for single-cell data. I used splatter to simulate data (default parameters + multiple groups + single batch) and used Seurat to cluster simulated cells into groups. 

I found that the cell groups assigned by Seurat are very different from the true cell group labels provided by splatter, even though the true groups are very obvious in the t-SNE embedding. In the following figure, the plot on the left is labeled by Seurat's clustering result, and the plot on the right is labeled as the true group label from splatter. Seurat split the big group, _Group1_ into two and combined two small groups, _Group 5_ and _Group3_. 

I am not sure if I used splatter correctly. If not, could you please help me understand how to improve the simulation?

<img src="https://user-images.githubusercontent.com/32473855/180100459-eb4f3a61-91bc-4fd5-b1ee-a7e9e20e1999.png" alt="drawing" width="400"/>

 Below I included my script for simulating and clustering.

```R
suppressPackageStartupMessages({
  library(splatter)
  library(Seurat)
})


params <- newSplatParams(group.prob = c(0.5, 0.2, 0.1, 0.1, 0.1)) 
sim.groups <- splatSimulate(params,
                            method = "groups",
                            verbose = FALSE)

resolution = 1.2
npcs = 10
nfeatures = 2000

seurat_object = CreateSeuratObject(counts(sim.groups))
seurat_object@meta.data$true_group <- sim.groups@colData$Group

seurat_object <- NormalizeData(seurat_object)
seurat_object <- FindVariableFeatures(seurat_object,
                                        selection.method = "vst",
                                        nfeatures = nfeatures)

seurat_object <- ScaleData(seurat_object,
                            features = rownames(seurat_object))

seurat_object <- RunPCA(seurat_object,
                        features = VariableFeatures(object = seurat_object), 
                        npcs = npcs,
                        verbose = verbose)

# run clustering and dim reduction
seurat_object <- FindNeighbors(seurat_object, dims = 1:pcs,verbose = verbose)
seurat_object <- FindClusters(seurat_object, resolution = resolution, verbose = verbose)
seurat_object <- RunUMAP(seurat_object, dims = 1:pcs, verbose = verbose)
seurat_object <- RunTSNE(seurat_object, dims = 1:pcs, verbose = verbose)
DimPlot(seurat_object, reduction = "tsne", label = TRUE, repel = TRUE, group.by = "seurat_clusters")   + 
DimPlot(seurat_object, reduction = "tsne", label = TRUE, repel = TRUE, group.by = "true_group")   
```

Best,
Dongze

**Comment by lazappi** [comment]
Hi @DongzeHE 

Thanks for giving a **{splatter}** a go! This is actually the kind of behaviour I would expect (and hope) to see from a simulation in that it highlights a weakness of the graph-based clustering that **{Seurat}** (and many commonly used packages) use. If clustering methods were always able to find the correct groupings that would be a sign that the simulation is too simple and not useful for evaluating/developing methods.

**Comment by DongzeHE** [comment]
Thank you so much for your reply @lazappi. This is really an interesting point!

Ok, now I understand that simulation tools like splatter are trying to generate data as real as possible. As far as I am aware, most clustering methods utilize either a deep learning model, like VAE, or PCA -> kNN graph based-model to cluster examples (cells, just pretending that I'm an ML folk ;p), and these two kinds of methods usually have similar behavior in the real world (even though a VAE-based method gave me a much messier result for the simulated data above). As both kinds of methods didn't do well, do you have any recommendations on which or what kind of clustering methods people should use in their single-cell analysis?

Best,
Dongze

**Comment by lazappi** [comment]
There are many clustering methods and I'm not going to advise which is most appropriate for your data. I suggest you look at existing benchmarking papers.

You might also need to use more quantifiable metrics for evaluating clusterings rather than just looking at the UMAP. The example you posted actually looks fairly good to me, even though it doesn't perfectly match the real labels.
