### ISSUE TITLE
Can I fix the  batch effects factor?

### ISSUE THREAD

**Issue by gerrardmai** [Oshlack/splatter#154]
I want to generate two sets of data. Each set of data will have its own base gene mean. but two sets of data share the same batch effects factor. How to generate the data?

**Comment by lazappi** [comment]
Please have a look at this vignette which explains all the parameters of the splat model https://bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splat_params.html.

If it is still unclear I may be able to help if you provide more details of the scenario you want to generate.

**Comment by lazappi** [comment]
I am going to close this now but please comment if you have further questions
