### ISSUE TITLE
Robustness of cell grouping

### ISSUE THREAD

**Issue by gokceneraslan** [Oshlack/splatter#16]
Up/down regulation of random genes is working a bit weird.

`plotPCA(splatSimulateGroups(groupCells=c(1000,1000), nGenes=21), colour_by='Group')` gives:

![image](https://cloud.githubusercontent.com/assets/1140359/26628526/af69d8f4-45fe-11e7-9684-10d95ea2d2bc.png)

whereas `plotPCA(splatSimulateGroups(groupCells=c(1000,1000), nGenes=22), colour_by='Group')` leads to:

![image](https://cloud.githubusercontent.com/assets/1140359/26628541/c1b31408-45fe-11e7-9207-df49a1b499c7.png)

Is this normal?

**Comment by gokceneraslan** [comment]
OK, this is not related to number of genes directly. Better question is why would these two so different:

`plotPCA(splatSimulateGroups(groupCells=c(1000,1000), nGenes=22, seed=1))`

`plotPCA(splatSimulateGroups(groupCells=c(1000,1000), nGenes=22, seed=2))`

**Comment by lazappi** [comment]
As this is more of a user issue I have answered it on the Bioconductor support site https://support.bioconductor.org/p/96502/#96503.
