### ISSUE TITLE
Is it possible to simulate condition effect without using splatpop?

### ISSUE THREAD

**Issue by yujias424** [Oshlack/splatter#163]
Hi,

Thank you for presenting this great package for single-cell data simulation. I wonder whether it is possible to simulate condition effect without using splatePop?

**Comment by lazappi** [comment]
The normal `splat` simulation allows you to generate "batches" which can sometimes be considered as conditions but are maybe not what you are looking for. Unfortunately, it doesn't currently support more flexible types of conditions. Some of the other simulation models in **{splatter}** have some limited support for conditions but generally lack other features.

**Comment by lazappi** [comment]
I'm going to close this issue but please reopen if you have further questions.
