### ISSUE TITLE
rownames/colnames not identical in `splatSimDropout()`

### ISSUE THREAD

**Issue by wanlinjuan** [Oshlack/splatter#167]
Hi,

I try to add dropouts to real data (seurat object). At first I convert the seurat object into singlecellexperiment object, then I use `splatSimDropout()` function.

Here is the error message:

```
Error in `assays<-`(`*tmp*`, value = `*vtmp*`) : 
  please use 'assay(x, withDimnames=FALSE)) <- value' or 'assays(x,
  withDimnames=FALSE)) <- value' when the rownames or colnames of the
  supplied assay(s) are not identical to those of the receiving
  SingleCellExperiment object 'x'
```

I check the rownames and colnames of the singlecellexperiment object. They are identical to the original seurat object. 

I also try to change the rownames to Gene1, Gene2, etc. And colnames to Cell1, Cell2, etc. But it still doesn't work. I would really appreciate your help.

**Comment by lazappi** [comment]
Hi @wanlinjuan

The `splatSimDropout()` function is really an internal function that isn't meant to be used directly by users. Instead it is part of the series of sub-functions called by `splatSimulate()`. I think the error is happening because it assumes there is an assay named "TrueCounts". Adding an assay with that name would help but the function also assumes other standard slots are present so it is likely you will get another, related error.

As in #88 I would question why you want to add dropout to a real dataset as this effect should already be present in real data. If you want to create a simulated dataset with dropout based on a real dataset you should use the `splatEstimate()` and `splatSimulate()` functions.

**Comment by wanlinjuan** [comment]
> Hi @wanlinjuan
> 
> The `splatSimDropout()` function is really an internal function that isn't meant to be used directly by users. Instead it is part of the series of sub-functions called by `splatSimulate()`. I think the error is happening because it assumes there is an assay named "TrueCounts". Adding an assay with that name would help but the function also assumes other standard slots are present so it is likely you will get another, related error.
> 
> As in #88 I would question why you want to add dropout to a real dataset as this effect should already be present in real data. If you want to create a simulated dataset with dropout based on a real dataset you should use the `splatEstimate()` and `splatSimulate()` functions.

Hi @lazappi! Thank you so much for your reply. I add a truecounts assay, and the error now is 
Error in true.counts * keep : non-conformable arrays

I checked the dimension of the count matrix and also the truecounts assay. It's consistent with the parameters for dropouts. I also convert the true counts assay to integer matrix.

For your question, I would like to use real data to evaluate some methods to address dropouts. But there is no ground truth for the real data. Additionally introducing dropouts can give us some insight how well these methods could work.

**Comment by lazappi** [comment]
> Hi @lazappi! Thank you so much for your reply. I add a truecounts assay, and the error now is Error in true.counts * keep : non-conformable arrays
> 
> I checked the dimension of the count matrix and also the truecounts assay. It's consistent with the parameters for dropouts. I also convert the true counts assay to integer matrix.

As I said, this is an internal function that isn't really meant to be used directly. You probably still have an inconsistency between the matrix and something else (maybe `params`). These lines show what information is used by that function https://github.com/Oshlack/splatter/blob/569f21399578f97696d45e16ce8114dc39f5d975/R/splat-simulate.R#L719-L729. 

> For your question, I would like to use real data to evaluate some methods to address dropouts. But there is no ground truth for the real data. Additionally introducing dropouts can give us some insight how well these methods could work.

I can understand that but I'm not sure it makes sense. The real data already contains this effect and then you are adding it again using this function. So you effectively have double "dropout". It may be safer to use a full simulation where there is more control of this.

**Comment by wanlinjuan** [comment]
> > Hi @lazappi! Thank you so much for your reply. I add a truecounts assay, and the error now is Error in true.counts * keep : non-conformable arrays
> > I checked the dimension of the count matrix and also the truecounts assay. It's consistent with the parameters for dropouts. I also convert the true counts assay to integer matrix.
> 
> As I said, this is an internal function that isn't really meant to be used directly. You probably still have an inconsistency between the matrix and something else (maybe `params`). These lines show what information is used by that function
> 
> https://github.com/Oshlack/splatter/blob/569f21399578f97696d45e16ce8114dc39f5d975/R/splat-simulate.R#L719-L729
> 
> .
> > For your question, I would like to use real data to evaluate some methods to address dropouts. But there is no ground truth for the real data. Additionally introducing dropouts can give us some insight how well these methods could work.
> 
> I can understand that but I'm not sure it makes sense. The real data already contains this effect and then you are adding it again using this function. So you effectively have double "dropout". It may be safer to use a full simulation where there is more control of this.

Hi @lazappi! Thank you so much for your explanations. Now I can successfully add dropouts. Here are the codes before adding dropouts:

colData(sim1)$Cell = colnames(sim1.s)
rowData(sim1)$Gene = rownames(sim1.s)
sim1@assays@data@listData$TrueCounts = count
sim1@assays@data@listData$CellMeans = count

sim1 is the singlecellexperiment object, and sim1.s is the seurat object. Hope the codes could be helpful for others!

**Comment by lazappi** [comment]
I think this is solved so closing the issue. Please reopen if needed.
