### ISSUE TITLE
Meaning of `sizeFactor` in colData?

### ISSUE THREAD

**Issue by kuang-da** [Oshlack/splatter#169]
Hi, 

Thank you for the great software. I am using 1.24.0, and I wonder what is the `sizeFactor` for? 

I am not able to find it either in this repo or in the documentation... Thank you for the clarification!
 
```
> head(colData(sim_groups))
DataFrame with 6 rows and 5 columns
             Cell       Batch    Group ExpLibSize sizeFactor
      <character> <character> <factor>  <numeric>  <numeric>
Cell1       Cell1      Batch1   Group2   1593.340   0.767023
Cell2       Cell2      Batch1   Group2   1672.968   0.874576
Cell3       Cell3      Batch1   Group2   2776.320   1.170347
Cell4       Cell4      Batch1   Group2   1294.759   0.569371
Cell5       Cell5      Batch1   Group2    726.105   0.424552
Cell6       Cell6      Batch1   Group1   1396.409   0.589655
```

**Comment by lazappi** [comment]
You are correct, `sizeFactor` is not part of the `splat` simulation. It is probably added during normalisation of the generated datasets (most likely by the **{scuttle}** package). Can you share the code you used to create this example? I'm wondering if it has happened as part of the simulation or by something you have done afterwards.

**Comment by lazappi** [comment]
I am closing this issue as there has been no response. If you have further questions please reopen it.
