### ISSUE TITLE
Library scale factors not saved in simulation?

### ISSUE THREAD

**Issue by ewaldvandyk** [Oshlack/splatter#171]
Splatter simulates scale factors randomly when setting param lib.scale != 0 and generating it with splatSimulateGroups, but it does not appear to save this ground truth information anywhere in my simulation. Is there a way to recover this information? I'm testing different normalisation algorithms and I need to know the ground truth scaling.

**Comment by ewaldvandyk** [comment]
Ah I see that you normalise the 'ground truth' gene abundances by library size before scaling it with a random expected library size. So I guess it's not possible to get the scaling factors I have in mind.

**Comment by lazappi** [comment]
Probably you are correct but I'm also not entirely sure what information you wanted. If you can explain a bit more there is a small chance I might be able to tell you how to get it.
