### ISSUE TITLE
scDD now uses SingleCellExperiment Objects

### ISSUE THREAD

**Issue by kdkorthauer** [Oshlack/splatter#23]
Hi,

I wanted to let you know that the [scDD package](https://github.com/kdkorthauer/scDD) has just been updated to use `SingleCellExperiment` instead of `SummarizedExperiment` objects. Specifically, the following three functions have modified input and/or output:

- The input and output object of the main `scDD` function has been changed from `SummarizedExperiment` to `SingleCellExperiment`
- The `simulateSet` function now directly returns a SingleCellExperiment object (previously it returned an object in list format)
- The `preprocess` function now takes as input a SingleCellExperiment object instead of a list of data frames

This may require some updates to any wrapper functions you've written that rely on these functions. Let me know if you have any questions or run into any trouble; I'm happy to help where I can.

Best,
Keegan

**Comment by lazappi** [comment]
Great! I'm hoping to find time to work on Splatter in the next week or two, I'll let you know if I have any questions.

**Comment by lazappi** [comment]
Fixed in b90aea2. Hopefully should be all good. Thanks for letting me know!
