### ISSUE TITLE
get counts data

### ISSUE THREAD

**Issue by chichaumiau** [Oshlack/splatter#24]
Hi Luke,
I am trying to use your github version. I cannot quite understand the results. I cannot find the assayData, which is supposed to include the simulated counts. 

Thank you!

**Comment by lazappi** [comment]
In the next release of Bioconductor the `SCESet` object previously used by `Splatter` is being replaced by the `SingleCellExperiment` object, this is probably the version you have installed from GitHub. This object does not have an `assayData` slot, please refer to the `SingleCellExperiment` documentation (https://bioconductor.org/packages/devel/bioc/html/SingleCellExperiment.html) and the development vignette (https://bioconductor.org/packages/devel/bioc/vignettes/splatter/inst/doc/splatter.html) for example of how to access the new object. Note that using the version will require you to have the development version of Bioconductor installed, see https://www.bioconductor.org/developers/how-to/useDevel/.
