### ISSUE TITLE
Allow cell-specific dropout parameters

### ISSUE THREAD

**Issue by willtownes** [Oshlack/splatter#25]
I would like to simulate dropouts varying across cells. Currently splatter accepts a single number for dropout.mid and dropout.shape. Could this be modified so that it accepts a numeric vector of length nCells for each of these?

**Comment by lazappi** [comment]
Hi, thanks for giving Splatter a go

It is probably possible, but I think if I was to change this I am more likely to make it a vector by group, similar to other parameters like `de.prob`. Do you have a use case for wanting to do this? Off the top of my head I'm not sure it makes sense to have different dropouts for each cell but I presume there is something you want to test?

**Comment by willtownes** [comment]
Thanks for making this package and for your fast response. My use case is to have some groups that are "biological" (I think this is already present in splatter) and then have two "technical batches": one batch has a high dropout threshold and the other has a low dropout threshold. I don't want the technical batches to be the same as the biological groups.

**Comment by lazappi** [comment]
Ok, that makes sense. Just in case you haven't seen it the development version of Splatter has added batch effects to the Splat simulation, although they don't work by modifying dropout so maybe that won't be useful for what you are doing.

Perhaps it makes sense to have the dropout parameters vectorised by batch? I think this might make sense as they are both technical effects?

**Comment by willtownes** [comment]
Vectorizing by batch is fine, although ideally I would like to just specify a different value for each cell. I am thinking of the parameters as random effects distributed around batch-level means.

**Comment by lazappi** [comment]
Ok. I'll try and have a look at this before the next Bioconductor release in a couple of weeks. There are a few other things on my list though, so I might not get to it before then.

**Comment by willtownes** [comment]
It's not an urgent need but I would be interested in trying it if not too much trouble for you to implement.

**Comment by lazappi** [comment]
I've had a go at this on a new branch here https://github.com/Oshlack/splatter/tree/dropout. The main change is replacing `dropout.present` with `dropout.type` which lets you choose the level for the other dropout parameters.

You should be able to install it using

``` r
devtools::install_github("Oshlack/splatter@dropout")
```
Can you give it a go and see if it does what you're looking for?

**Comment by lazappi** [comment]
Hi @willtownes, just wondering if you have had a chance to look at this yet? If it is working for you I would like to merge it into the development version, but it will need to be done in the next couple of days to make the next Bioconductor release.

**Comment by willtownes** [comment]
OK I have [experimented](https://gist.github.com/willtownes/3fb06b305d2db70476404d677e308cca) with this a bit and it seems fine. The only issue I found was that the scater plotPCA function expects an assay called "logcounts" which is not currently generated by the simulation. Not a big deal but just thought you should know. So feel free to close out the issue. Thanks for adding the feature! 

``

**Comment by lazappi** [comment]
Cool. I've pushed a new version that should be in Bioconductor devel in the next couple of days and then the next release. 

I don't make the logcounts assay because not everyone needs it. I usually just use `scater::normalise` before `plotPCA`.
