### ISSUE TITLE
simulate batch effect

### ISSUE THREAD

**Issue by chichaumiau** [Oshlack/splatter#26]
Hi Luke,
How can I simulate batch effect with splatter? I got an error "could not find function "splatSimBatchEffects"" when I call the function. 

Which version of splatter shall I use to repeat the batch simulation in your paper?

Best,

**Comment by lazappi** [comment]
Hi

Thanks for giving Splatter a go.

Batch effects were added after the last Bioconductor release. Please check the version you have installed (using `sessionInfo()`), if it starts with `1.0` you will need to install a newer version.

The version used in the paper can be installed using `devtools::install_github("Oshlack/splatter@v1.1.3-basics")`. The latest version can be installed using `devtools::install_github("Oshlack/splatter")`, but note this will require the development version of Bioconductor (see https://www.bioconductor.org/developers/how-to/useDevel/) so is not recommended.

The other option is to wait for the next Bioconductor release at the end of the month.

Good luck!

**Comment by chichaumiau** [comment]
Hi Luke,
Thank you for the answer!
I am just wondering, how can I simulate 3 groups of cells of 100, 200, 300 cells, while each of them have different number of batches. 

Best,

**Comment by chichaumiau** [comment]
Thank you for the explanation!
I tried to simulate 3 batches with Splatter: using the codes:
sim <- splatSimulateGroups(batchCells = c(192,192,192),
                                   group.prob = c(0.33, 0.33,0.34),
                                   de.prob = c(0.1, 0.1, 0.1),
                                   de.facLoc = 0.1,
                                   de.facScale = 0.4,
                                   dropout.present = TRUE,
                                   seed = 10)
But the result is not 'batchy' as expected. 
What parameters are expected?

**Comment by lazappi** [comment]
That code looks correct to me. You might want to play around with the `batch.facLoc` and `batch.facScale` parameters to increase the batch effect.
