### ISSUE TITLE
Control group size 

### ISSUE THREAD

**Issue by philipvk** [Oshlack/splatter#27]
I have been using the following code to simulate different groups of single cells": 

`splatter_sim_1 <- splatSimulateGroups(groupCells = c(100, 100, 100, 100, 100),
                                      nGenes = 500,
                                      de.prob = c(0.05, 0.05, 0.05, 0.05, 0.05), 
                                      de.facLoc = 3, de.facScale = 0,
                                      dropout.present = TRUE,
                                      seed = 1)`

Since the update to R version 3.4 and the newest Bioconductor version this code gives an error:

> Error in checkSlotAssignment(object, name, value) : ‘groupCells’ is not a slot in class “SplatParams”

I am not sure how to write code in the new version, which simulates different groups. Can someone help me?

**Comment by lazappi** [comment]
As this is a question about usage I have answered it on the Bioconductor support site https://support.bioconductor.org/p/102767/#102768
