### ISSUE TITLE
Error when using scDDEstimate

### ISSUE THREAD

**Issue by homopolymer** [Oshlack/splatter#39]
I tried the example code to generate scDD simulation data, but encountered the following error:
> data("sc_example_counts")
> conditions <- sample(1:2, ncol(sc_example_counts), replace = TRUE)
> params <- scDDEstimate(sc_example_counts, conditions = conditions)
>>Error in scDDEstimate(sc_example_counts, conditions = conditions) : 
>>  Assertion on 'params' failed: Must have class 'SCDDParams', but has class 'character'.

I have tried the version 1.3.2 and version 1.2.0 of splatter. Both have this error.

Here are traceback info:
> traceback()
7: stop(simpleError(sprintf(msg, ...), sys.call(1L)))
6: mstop("Assertion on '%s' failed: %s.", var.name, res)
5: makeAssertion(x, res, .var.name, add)
4: checkmate::assertClass(params, "SCDDParams")
3: scDDEstimate.default(counts, "condition", params, verbose, BPPARAM)
2: scDDEstimate.matrix(sc_example_counts, conditions = conditions)
1: scDDEstimate(sc_example_counts, conditions = conditions)

**Comment by lazappi** [comment]
This was my fault, there was a bug in how I was passing some of the parameters around. Thanks for catching it!

This has been fixed in v1.2.2 (release) and v1.3.3 (devel). They should make it to Bioconductor in the next day or so.
