### ISSUE TITLE
Fixing gene means

### ISSUE THREAD

**Issue by ilyakorsunsky** [Oshlack/splatter#40]
First, thanks for creating this beautifully organized simulation system! I would like to run a cell type specific splat simulation, with the (relative) gene means estimated from real data. From the paper, it looks like I could set the lambda_i parameters, assume the rest of the gene specific parameters are exchangeable, and simulate the rest of the model as is. Can I do this in splatter as it is built? If not, where in the code would you start to add this functionality? I would be happy to contribute any features I build with this.

**Comment by ilyakorsunsky** [comment]
Thanks for the quick reply! Yup, that's exactly what I'd like to do. So far, I set base.means.gene in splatSimGeneMeans with the winsorized gene means from my library-size normalized count matrix. However, when I run a simulation, the resulting gene means don't match my original means. This makes sense, since the simulated means are subject to outlier and dropout noise. Still thinking about how to approach this; any suggestions would be much appreciated!

**Comment by lazappi** [comment]
I have created a modified version of `splatSimulate` here https://gist.github.com/lazappi/6d41820d78716fd952e0780b37fae63f that allows you to supply a vector of gene means. The section I changed starts on Line 83. I haven't tested it thoroughly but I think it should work. Make sure you are using the latest release version of Splatter (v1.2.2).

I will add the Splat simulation isn't really designed to work this way. You might want to look at something like the Lun2 simulation (`lun2Estimate` and `lun2Simulate`) that already does something similar to what you want. Let me know how you go.

**Comment by lazappi** [comment]
Hi @ilyakorsunsky 

Have you had a chance to check this out? Just wondering if it worked for you or not.

**Comment by ilyakorsunsky** [comment]
Thanks for this, it seems to do the trick! Playing around with this, I also found it useful to transform (with the inverse CDF method) my gene means distribution into the gamma distribution estimated by Splat. This makes the data retain some more of the single-cell-ness parametrically.

**Comment by lazappi** [comment]
Sorry I got this mixed up with #25. I don't have plans to add this to the Bioconductor version of splatter at this stage, I think it is too big of a change to the Splat model. 

If this is working for you are you happy for me to close this issue?

**Comment by ilyakorsunsky** [comment]
Absolutely, thanks for your help!
