### ISSUE TITLE
simulating paths returns identical values

### ISSUE THREAD

**Issue by galicae** [Oshlack/splatter#41]
I was trying to simulate a differentiation, and followed the instructions for paths in [Introduction to Splatter](https://bioconductor.org/packages/devel/bioc/vignettes/splatter/inst/doc/splatter.html#simulating-paths). However, when I then looked at the data with `assay(sim.paths)`, I was greeted by a matrix where all columns (cells) had identical values. Am I doing something wrong? I was hoping to eventually simulate more complex lineage trees.

The code in question:
```
library(splatter)

sim.paths <- splatSimulate(method = "paths", verbose = FALSE)
sim.paths <- normalise(sim.paths)
View(assay(sim.paths))
```

**Comment by lazappi** [comment]
Hi @galicae 

Thanks for giving Splatter a go. As this is more a question about using Splatter than an issue I have answered it on the Bioconductor support site here https://support.bioconductor.org/p/107796/#107798.

Feel free to comment there if you need any further clarification.

**Comment by galicae** [comment]
fair enough, thanks for the tip!
