### ISSUE TITLE
accessing normalized counts

### ISSUE THREAD

**Issue by galicae** [Oshlack/splatter#42]
When I try to access the normalized counts from a path simulation, I get the following error:
```
Error in assay(object, i = exprs_values) : 
  'assay(<SingleCellExperiment>, i="character", ...)' invalid subscript 'i'
'i' not in names(assays(<SingleCellExperiment>))
```

The code that creates the issue is as follows:

```
sim.paths <- splatSimulate(method="paths")
sim.paths <- normalise(sim.paths)
normX <- normcounts(sim.paths)
```

**Comment by lazappi** [comment]
Hi @galicae 

I've answered this on Bioconductor as well https://support.bioconductor.org/p/107846/#107847.
