### ISSUE TITLE
Any pointer on simulating cell outliers?

### ISSUE THREAD

**Issue by logstar** [Oshlack/splatter#47]
I was wondering if it is possible to use Splatter to simulate cell outliers. 

In the documentation of Splatter, there are expression outlier parameters, but I did not find any specific information on cell outliers. Excuse me if I missed anything. I only searched the keyword "outlier" in the documentation.

I thought about generating very small DE groups with large DE scale in Splatter as cell outliers, but I am not sure if it is appropriate or not.

I am trying to benchmark methods for detecting cell outliers. Although it is not very meaningful to identify a very small number of outliers in scRNA-seq datasets that usually contain thousands of cells, it may be a straightforward approach to reduce the noise in the datasets.

Any pointers would be appreciated! 

By the way, I have been using Splatter to benchmark clustering methods, and it worked very smoothly. I appreciate your efforts on making the package reliable and easy to use.

**Comment by lazappi** [comment]
Hi @logstar 

Thanks for giving Splatter a go! I hope it can be useful for your situation. As this is mostly a question about usage I have answered it on the Bioconductor support site here https://support.bioconductor.org/p/109014/#109016. Feel free to post any further questions/comments there.

**Comment by logstar** [comment]
Hi @lazappi

Thank you for the prompt reply! I have read your answer on the Bioconductor support site, and it is very helpful. I will start trying the approach you outlined and look further into other DE parameters. 

I will follow up on your Bioconductor post if I have any further question.
