### ISSUE TITLE
Identical values for simulated cells

### ISSUE THREAD

**Issue by jasonserviss** [Oshlack/splatter#52]
I thought I would give this package a try to generate some simulated data but hit a roadblock pretty quickly... For an initial attempt I wanted to generate data for 3 groups. 

``` r
suppressPackageStartupMessages(library(splatter))

sim.groups <- splatSimulate(
  nGroups = 3, method = "groups", verbose = FALSE
)
#> Error in setParam(params, name, value): nGroups cannot be set directly, set group.prob instead
```
This didn't work so I instead attempted to, as instructed, set the group.prob parameter. As far as I understand the documentation, "The probabilities that cells come from particular groups." and associated example in the vignette (that says: "As we have set both the group probabilites to 0.5 we should get approximately equal numbers of cells in each group (around 50 in this case)."), I would expect that setting this parameter, as I do below, would result in approximately the same number off cells being generated for each group. 

``` r
n.groups <- 3
sim.groups <- splatSimulate(
  group.prob = rep(1 / n.groups, n.groups), method = "groups", verbose = FALSE
)
exp <- assay(sim.groups)
exp[1:5, 1:5]
#>            Cell1      Cell2      Cell3      Cell4      Cell5
#> Gene1 5.15303680 5.15303680 5.15303680 5.15303680 5.15303680
#> Gene2 0.15696057 0.15696057 0.15696057 0.15696057 0.15696057
#> Gene3 6.95742555 6.95742555 6.95742555 6.95742555 6.95742555
#> Gene4 0.05225995 0.05225995 0.05225995 0.05225995 0.05225995
#> Gene5 2.69473598 2.69473598 2.69473598 2.69473598 2.69473598
identical(exp[, 1], exp[, 2])
#> [1] TRUE
```

Although, this results in identical values being returned for each cell which, to me, seems odd. I would not have expected any of the cells to have identical expression values, even if they are in the same group. Would be grateful to know what is "going wrong" here and, hopefully, this issue could help indicate places in the vignette where a bit more information could be useful to future users.

Kind Regards,
Jason

``` r
sessionInfo()
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS High Sierra 10.13.5
#> 
#> Matrix products: default
#> BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] parallel  stats4    stats     graphics  grDevices utils     datasets 
#> [8] methods   base     
#> 
#> other attached packages:
#>  [1] splatter_1.4.1              SingleCellExperiment_1.2.0 
#>  [3] SummarizedExperiment_1.10.1 DelayedArray_0.6.1         
#>  [5] BiocParallel_1.14.2         matrixStats_0.53.1         
#>  [7] Biobase_2.40.0              GenomicRanges_1.32.3       
#>  [9] GenomeInfoDb_1.16.0         IRanges_2.14.10            
#> [11] S4Vectors_0.18.3            BiocGenerics_0.26.0        
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_0.12.17           bindr_0.1.1            pillar_1.2.3          
#>  [4] compiler_3.5.1         plyr_1.8.4             XVector_0.20.0        
#>  [7] bitops_1.0-6           tools_3.5.1            zlibbioc_1.26.0       
#> [10] digest_0.6.15          tibble_1.4.2           evaluate_0.10.1       
#> [13] checkmate_1.8.5        gtable_0.2.0           lattice_0.20-35       
#> [16] pkgconfig_2.0.1        rlang_0.2.1            Matrix_1.2-14         
#> [19] yaml_2.1.19            bindrcpp_0.2.2         GenomeInfoDbData_1.1.0
#> [22] dplyr_0.7.6            stringr_1.3.1          knitr_1.20            
#> [25] locfit_1.5-9.1         tidyselect_0.2.4       rprojroot_1.3-2       
#> [28] grid_3.5.1             glue_1.2.0             R6_2.2.2              
#> [31] rmarkdown_1.10         purrr_0.2.5            ggplot2_3.0.0         
#> [34] magrittr_1.5           backports_1.1.2        scales_0.5.0          
#> [37] htmltools_0.3.6        assertthat_0.2.0       colorspace_1.3-2      
#> [40] stringi_1.2.3          RCurl_1.95-4.10        lazyeval_0.2.1        
#> [43] munsell_0.5.0
```

Created on 2018-07-10 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by lazappi** [comment]
Hi @jasonserviss 

Thanks for giving Splatter a go and sorry for the slow reply, I've been away at conferences the last couple of weeks.

By default the `assay` function returns the first matrix in the assay slot. You can see what assays are available using the `assayNames` function.

```{r}
assayNames(sim.groups)
[1] "BatchCellMeans" "BaseCellMeans"  "BCV" "CellMeans" "TrueCounts" "counts" 
```

So, in this case, it is returning `BatchCellMeans` one of the intermediate matrices created during the simulation. Because you haven't specified any batch effects this looks the same for all cells. What you probably want is the `counts` assay.

```{r}
counts <- assay(sim.groups, "counts")
counts[1:5, 1:5]

      Cell1 Cell2 Cell3 Cell4 Cell5
Gene1     2     0     1     0     5
Gene2     4     5     1     6     5
Gene3     0     4     0     0     0
Gene4     0     0     1     0     0
Gene5     0     0     0     0     0
```

You can also access this directly using the `counts` function.

```{r}
counts <- counts(sim.groups)
```

Hope that helps!

**Comment by jasonserviss** [comment]
Yep, that explains it. Guess it has been too long since I have been working with SummarizedExperiment objects... Sorry for the noise.

**Comment by lazappi** [comment]
No worries, good luck with whatever you are working on.
