### ISSUE TITLE
Can I get DE gene list for a simulated data set?

### ISSUE THREAD

**Issue by tengfei-emory** [Oshlack/splatter#57]
I am conducting simulations to evaluate DE gene detection performances. Is it possible to know which genes are differentially simulated among groups, so that I can have a gold standard to compare with? I appreciate your support! Thank you.

**Comment by lazappi** [comment]
For the Splat simulation you need to consider the `DEFacGroupX` columns in the row metadata. These tell you whether the expression of a particular gene has been changed in a particular group. If you have simulated two groups then a positive DE factor indicates that a gene is up-regulated in that group (and down-regulated for negative factors). It gets a bit more complicated if you have multiple groups. Other models return different information about intermediate parameters.

**Comment by tengfei-emory** [comment]
Thank you for answering! Could you please explain the complication when I simulate multiple groups? When comparing only two groups out of many groups, is it reasonable to ignore the DE factor for other groups and focus only on the two groups of interest? Your advice will be really helpful for our analyses. Thank you again.
