### ISSUE TITLE
simulate counts with varying dropout rates

### ISSUE THREAD

**Issue by mkrzak** [Oshlack/splatter#60]
Hello,
I would like to simulate counts with varying dropout rates. I varied dropout.shape and/or dropout.mid parameters and checked percentage of zeros in my counts but it seems to be always the same. After introducing new parameters I see they are updated with NOT DEFAULT. I also estimated parameters after simulation and the MIDPOINT is close to 0 and SHAPE is close to -1 as in default parameters. Is there anyone who can have an idea what can cause the problem?
Monika

PS For reproducibility Im using set seed. Once I change the seed of course dropout rate is changing. What I wish to obtain is the same counts with "different amounts of zeros".

**Comment by lazappi** [comment]
Hi @mkrzak Thanks for giving Splatter a go, hopefully I can help you our. I just want to clarify what you are trying to do to make sure I am answering the right question. I think what you want to do is generate a single dataset and then apply different levels of dropout to it? Is this correct? It might be helpful if you could provide some code with an example of what you have been trying so far.

**Comment by mkrzak** [comment]
Hi @lazappi thanks for your fast reply. Yes, exactly this is my aim. Here is the code that I was testing for dropout.mid, I did also the same with varying dropout.shape. The counts and generated number of zeros are always the same.

`library(splatter)
dropout.mid=c(-10,-5,0,5,10)
for(i in 1:length(dropout.mid)){
params <- newSplatParams()
params <- setParams(params,  nGenes=1000, batchCells=1000, group.prob = c(0.25,0.25,0.25,0.25), seed=100, dropout.mid=dropout.mid[i])
data <- splatSimulate(params, method = "groups", verbose = FALSE)
count_zeros <- function(x){length(which(x==0))}
zeros=apply(counts(data), 2, count_zeros)
print(counts(data)[1:4,1:4])
print(zeros[1:4])
print(data@metadata$Params@dropout.mid)
est_params <- splatEstimate(data)
print(est_params@dropout.mid)
}
`

**Comment by lazappi** [comment]
Thanks for the code. I tried running it and got the same results so it looks like there is a bug somewhere. Perhaps the dropout parameters are not being passed along properly somewhere or being overwritten but I will take a look and see if I can work it out.

**Comment by mkrzak** [comment]
Dear @lazappi, thanks it works perfectly!

**Comment by lazappi** [comment]
Great! I'm going to close this issue now but feel free to comment or open a new one if you have more questions. 🎄

**Comment by nderituc** [comment]
hi lazappi,
How do we  set a dropout rate using splatter like 50.3%

**Comment by lazappi** [comment]
@nderituc Please see this vignette for a description of all the parameters in the Splat model https://bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splat_params.html. If you are still unsure please open a new issue.

**Comment by lazappi** [comment]
@nderituc Please open a new issue or post on the [Bioconductor support forum](https://support.bioconductor.org/). Asking new questions here confuses the conversation.

**Comment by AFMShamsuzzaman** [comment]
How to set dropout rate using splatSimDropout function of splatter ?

**Comment by lazappi** [comment]
@AFMShamsuzzaman `splatSimDropout()` is an internal function that is not really meant to be used directly, instead you should use the `splatSimulate()` function. Please see this vignette for a description of all the parameters in the Splat model [bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splat_params.html](https://bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splat_params.html). If you are still unsure please open a new issue or post on the [Bioconductor support forum](https://support.bioconductor.org/) to ask your specific question.

**Comment by AFMShamsuzzaman** [comment]
> @AFMShamsuzzaman `splatSimDropout()` is an internal function that is not really meant to be used directly, instead you should use the `splatSimulate()` function. Please see this vignette for a description of all the parameters in the Splat model [bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splat_params.html](https://bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splat_params.html). If you are still unsure please open a new issue or post on the [Bioconductor support forum](https://support.bioconductor.org/) to ask your specific question.

I want to set dropout rate. Is it possible to set dropout rate using splatSimulate() function ?

**Comment by lazappi** [comment]
This is explained in the [parameters vignette](https://bioconductor.org/packages/release/bioc/vignettes/splatter/inst/doc/splat_params.html). If that is not clear please open a new issue.
