### ISSUE TITLE
`de.downProb` is mislabeled in docs as `de.loProb`

### ISSUE THREAD

**Issue by scottgigante** [Oshlack/splatter#64]
`de.downProb` is mislabeled in docs as `de.loProb`. 

See https://bioconductor.org/packages/devel/bioc/vignettes/splatter/inst/doc/splatter.html#parameters and https://github.com/Oshlack/splatter/blob/master/R/AllClasses.R#L129

**Comment by lazappi** [comment]
Thanks for catching that! I'll make sure it's fixed in the next release.
