### ISSUE TITLE
path.length has no apparent effect on data variance

### ISSUE THREAD

**Issue by dburkhardt** [Oshlack/splatter#68]
Hi, I decided to give Splatter a go to use as the basis for a quantitative comparison for a computational method I'm developing (shameless plug: www.github.com/krishnaswamylab/MELD).

I want to simulate paths of various lengths and density. Here, I'm using length to describe the variation along the path. For example, if a gene goes up by 0.1 every Step of the path, then a path of length 1000 should have greater variance than one of length 10, even if they contain the same number of cells. However, this is not what I find.

Using the following commands:
```
# Imports
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("splatter", version = "3.8")
library(splatter)
if (!require(viridis)) install.packages("viridis")
if (!require(ggplot2)) install.packages("ggplot2")
# Using some tools here for library size normalization
library(phateR)

# Set parameters for simulation
params <- newSplatParams()
params <- setParam(params, "batchCells", 1000)
params <- setParam(params, "nGenes", 5000)
params <- setParam(params, "group.prob", c(0.5,0.5))
params <- setParam(params, "path.length", c(10,1000))

# Run simulation
sim <- splatSimulate(params, method = "paths", verbose = FALSE)

# Get counts and transpose
data <- t(counts(sim))

# Library size normalize (divide row-wise by L1 norm)
data <- library.size.normalize(data)

# Sqrt transform
data <- sqrt(data)

# Get PCA decomposition
data_pca <- as.data.frame(prcomp(data)$x)

# Plot the groups
ggplot(data_pca) +
  geom_point(aes(PC1, PC2, color=sim$Group)) +
  labs(color="Group")

# Plot the steps
ggplot(data_pca) +
  geom_point(aes(PC1, PC2, color=sim$Step)) +
  labs(color="Step") +
  scale_color_viridis(option="B")
```

I get the following images:

![image](https://user-images.githubusercontent.com/8322751/55750352-17b20f80-5a11-11e9-973a-03f6a621d345.png)

Here, you can see that on the first two PCs, the groups are pretty fairly split and that the length of the two paths are fairly uniform in terms of their PC loadings.

I can also confirm that the Step assigned to each cell is accurate.
![image](https://user-images.githubusercontent.com/8322751/55750431-462fea80-5a11-11e9-936c-e1e59cb87d58.png)

What's going on here? Do I misunderstand the path length parameter? I would like to simulate data in such a way that one "branch" of my dataset is longer than the other. I also want to vary the density of these branches independently of the length of them.

Please let me know if there's a way to get this functionality using Splatter.

Thanks,
Dan

**Comment by lazappi** [comment]
Hi @dburkhardt 

Thanks for giving Splatter a go, hopefully we can come up with a set of parameters that does what you want. I imagine the `path.length` parameter as the time it takes for one cell type to differentiate into another. We might want to describe two processes where one is fast and the other is slow so we would set a short `path.length` for the first one and a long `path.length` for the second. To describe how different each endpoint is (which is what I think you want to do) you would want to change the parameters controlling differential expression along the path (`de.prob`, `de.facLoc` and `de.scale`). Each of these can be given different values for each path.

Hope that helps

**Comment by dburkhardt** [comment]
Interesting, I hadn't thought about path length in that way. I've done some more experimenting, and from what I can tell, `path.length` varies the granularity/resolution of a path. So if you have a `path.length` of 5 with 1000 cells, then you will by definition have ~200 cells per "step".  However if you have `path.length` of 1000 with 1000 cells then you will have ~1 cell per "step". 

I'm not sure this is what we want. Unless I misunderstand something, in this model each path is a series of discrete steps, where decreasing `path.length` simply makes the process more discrete. I would argue that differentiation in biology is a continuous process, it only appears discrete when we sample it. If one differentiation process is happening faster than another in the same system, then both are still continuous, but if we sample from both, then we would expect to observe fewer in the "faster" path.

I think this interpretation is supported by the literature. I don't know if you have come across the RNA velocity paper from Peter Kharchenko's lab ([PMID: 30089906](https://www.ncbi.nlm.nih.gov/pubmed/30089906)), but it provides a great system for thinking about differentiation "speed". They used introns identified in scRNA-seq data to estimate active transcription in three different developmental systems. You can see in figures 2, 3, and 4 that the "differentiation bridges" connecting the endpoints are 1) less dense than the endpoints and 2) have more active transcription (i.e. are more quickly changing state) and 3) represent continuous intermediate states.

I've run a few more simulations varying this path length parameter and I hope I can convince you that we don't really want to vary the "discreteness" of the path.

**5000 cells sampled from a path of 1000 steps (10K genes)**
![image](https://user-images.githubusercontent.com/8322751/55809784-84cab100-5ab4-11e9-86f8-d7eea18cc904.png)

I think this is a good baseline path. We observe a clear set of intermediate state between two endpoints. Now let's say at the want this process to occur faster. According to the current `path.length` setup, we should decrease the number of steps to get a "faster" differentiation process.

**5000 cells sampled from a path of 5 steps (10K genes)**
![image](https://user-images.githubusercontent.com/8322751/55809901-b93e6d00-5ab4-11e9-8233-09b9e522fedb.png)

I know that picking 5 steps is pathological, but here we see something that doesn't fit the model of biology that I understand. Instead of having a path that represents a continuous progress, we're actually seeing a discrete set of 5 cell states. 

My assertion is that we would rather simply decrease the number of cells sampled between the end states. Let's do that in the next simulation.

**100 cells sampled from a path of 1000 steps (10K genes)**
![image](https://user-images.githubusercontent.com/8322751/55810302-58636480-5ab5-11e9-84cf-9f0bc24010d4.png)

I think this is a much closer match to biology. You can see that this process is more "discrete" in that there are many fewer cells at the intermediate time points, but the process is still continuous.

Now as a bonus, I think it would be even nicer if there was a way to set paths so that the intermediate states are less dense than the end points. I've done this here by simply remove points at intermediate states.

**5000 cells sampled from a path of 1000 steps with subsampling in the middle**

![image](https://user-images.githubusercontent.com/8322751/55811156-af1d6e00-5ab6-11e9-8a64-331d4232a637.png)

Here I set the probability of a cell being captured to be lower at the intermediate state. I think this is probably the best way to vary the "speed" of differentiation. I think both theoretically this makes the most sense and the results are most similar to what I see when I'm working with single cell data.

**Suggestion**
I know this is a huge ask, but I think Splatter would be more relevant for the community if `path.length` were a parameter that varies the `de.prob` and `de.facLoc` parameters that you suggested above. I did test this, and it's possible to get paths of varying length (i.e. varying distance between endpoints) by increasing `de.facLoc`. However, I'm not sure this is an intuitive way for new users to increase distance between paths for new users.

I would be happy to talk more about this, and I greatly appreciate all of the work that you've put into splatter. As a computational biologist developing methods, it's great to have access to high-quality ground-truth simulation tools. Our group is actually developing a python wrapper for splatter that we would increase the accessibility of splatter to the python community of programmers (https://github.com/KrishnaswamyLab/scprep/blob/dev/scprep/run/splatter.py).

Thanks again,
Dan

**Comment by lazappi** [comment]
Hi Dan

Thanks for your comments, it's great to hear from someone who has thought about this in a lot of detail.

I think you are right about the `path.length` parameter affecting the discreteness of the path and some of the other parameters being more useful for changing what the path looks like. This is probably a result of how I developed the simulation originally. I basically started with a simulation of discrete groups and then thought about how I could modify it to make it more continuous which is how I came up with this idea of "steps" along a path. It might be worthwhile developing a fully continuous version (and there are probably some simulations like that out there already).

Another parameter that might be worth looking at is the `path.skew` parameter. What this does is adjust the probability of a cell coming from a particular step so that they are skewed towards one end or the other (if that makes sense). I think this is kind of like what you have done by adjusting the density but only in one direction along the path rather than a lower density in the middle. You might be able to get a similar effect by having two paths (progenitor -> intermediate -> differentiated) and skewing them towards the start and end points.

Cool to see a Python wrapper, that would be excellent! Let me know if there is any way I can help out. Happy to hear any other suggestions as well, I'm hoping to do a bit of work on Splatter before the next Bioconductor release (April 24).

**Comment by dburkhardt** [comment]
Absolutely. I think it's a very useful tool. I guess I should also be clear that I don't want to advocate for a fully continuous path. Because we're adding continuous noise to each intermediate step, setting steps to something like 1000 or 10000 should be sufficient for all but the longest paths one might want to simulate. 

I also want to emphasize that two other people in our group have used splatter, and based on the documentation they were under the impression that `path.length` would vary the length of the path (i.e. change the distance between the endpoints). Perhaps a better name for this variable would be `path.steps`? Along with some change in the documentation stating exactly what the parameter does, I think this would be helpful for users using the "paths" functionality.

As for the skew parameter, I've noticed something a little surprising. If I generate two paths using `de.facLoc=c(0.1,1)` and set `path.nonLinearProb=0`, I still see some difference in density (i.e. skew) when I visualize it.

![image](https://user-images.githubusercontent.com/8322751/55891730-1143a500-5b83-11e9-8129-da5af2d1f7d2.png)

See on the KDE plot on the right, there's a skew in density to far end. Have you seen this before? Do you know why this would be?

The exact parameters I used are:
```
'method':'paths', 'batch_cells':cells_per_path * n_groups, 'seed':7, 
          'path_length':1000, 'group_prob':np.tile(1/n_groups, n_groups), 'path_from':0, 'de_fac_loc':[0.1, 1], 'path_skew'=0.5,  'path_nonlinear_prob':0 ,'n_genes':10000
```

I'll send you an email about coordination on the Python wrapper. We would be happy to spin that off into it's own package that you could maintain if you wanted.

**Comment by lazappi** [comment]
I renamed the parameter to `path.nSteps` in the latest release. I'm going to close this now but happy to continue the discussion if there is anything else.
