### ISSUE TITLE
Errors in the example.

### ISSUE THREAD

**Issue by ikwak2** [Oshlack/splatter#7]
Dear package developer, 

I am following your vignettes and am facing these error messages.
I am using R version 3.3.2 and splatter v0.99.0. 

 > params <- splatEstimate(sc_example_counts)
 > sim <- splatSimulate(params, dropout.present = FALSE)
 Getting parameters...
 Creating simulation object...
 Simulating library sizes...
 Simulating gene means...
 Simulating BCV...
 Simulating counts..
 Simulating dropout...
 Creating final SCESet...
 Error in validObject(object) :
   invalid class “SCESet” object: 1: featureNames differ between assayData and featureData
 invalid class “SCESet” object: 2: sampleNames differ between assayData and phenoData
 >

Thank you!
Sincerely,
ilyoup (andy)

**Comment by lazappi** [comment]
Hi ilyoup

Thanks for trying out the package, that should definitely not be happening. It looks like it might be the same problem as in #5. Can you please run `sessionInfo()` and send me the output?

Luke

**Comment by ikwak2** [comment]
Yes, it is the same problem. I upgraded scater to the newest version as you suggested and the problem solved! 
Thank you! 

Before 
> sessionInfo()
 R version 3.3.2 (2016-10-31)
 Platform: x86_64-apple-darwin13.4.0 (64-bit)
 Running under: OS X El Capitan 10.11.6

 locale:
 [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

 attached base packages:
 [1] parallel  stats     graphics  grDevices utils     datasets  methods
 [8] base

 other attached packages:
 [1] splatter_0.99.0     scater_1.0.4        ggplot2_2.2.1
 [4] Biobase_2.32.0      BiocGenerics_0.18.0


After (problem solved)
!> sessionInfo()
 R version 3.3.2 (2016-10-31)
 Platform: x86_64-apple-darwin13.4.0 (64-bit)
 Running under: OS X El Capitan 10.11.6

 locale:
 [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

 attached base packages:
 [1] parallel  stats     graphics  grDevices utils     datasets  methods
 [8] base

 other attached packages:
 [1] splatter_0.99.0     scater_1.2.0        ggplot2_2.2.1
 [4] Biobase_2.34.0      BiocGenerics_0.20.0

**Comment by lazappi** [comment]
Great! Good splattering! If you run into any more problems or have suggestions for new features please open another issue.
