### ISSUE TITLE
Mean-variance relationship and zero-count genes

### ISSUE THREAD

**Issue by gdagstn** [Oshlack/splatter#71]
Hi Luke,
great software and documentation. 
I was playing around with splatter and there are some things that I might be doing wrong or I plainly don't understand.
I loaded filtered count data from the [1K PBMCs provided by 10X genomics](https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/pbmc_1k_v3), and removed genes with all zeroes:

```r
library(splatter)
library(scater)
library(DropletUtils)
library(LSD)

#load 10x 4k PBMC filtered data
tmp <- read10xCounts("./pbmc_1k_filtered_feature_bc_matrix")

#need to convert it to dense data to be read by splatter
tmp_dense <- as.matrix(assay(tmp))
assay(tmp) <- tmp_dense

dim(tmp)
# [1] 33538  1222

#Remove genes with 0 counts in all cells
keep <- nexprs(tmp, byrow = T) > 0
tmp <- tmp[keep,]

dim(tmp)
#[1] 18391  1222
```

I then estimate parameters using `splatter::splatEstimate` (I am interested in the common dispersion):

```r
# Estimate parameters from the data
params <- splatEstimate(tmp)

disp.sp <- params@bcv.common
disp.sp
#[1] 0.250343
```

Then I estimate dispersion in a different way, i.e. fitting the quadratic relationship between dispersion, mean and variance  _Var = mean * (1 + mean * dispersion)_ using non-linear least squares (which is how I think Valentine Svensson does in his [blog post](http://www.nxn.se/valent/2017/11/16/droplet-scrna-seq-is-not-zero-inflated) about the NB nature of single cell RNA-seq data):

```r
#Look at mean-variance relationship in raw counts

count.vars <- rowVars(assays(tmp)$counts)

count.means <- rowMeans(assays(tmp)$counts)

#Alternative estimation by non-linear least squares
est.nls <- nls(count.vars ~ count.means * (1 + (count.means * x)), start = list(x = 0.01))

disp.nls <- summary(est.nls)$coefficients[1]
#[1] 0.6195632
``` 
Moreover, I calculate the uncorrected dispersion as `edgeR` does, and plot the mean-variance scatterplot together with the trend lines for the `nls` and the `splatter` dispersion estimates (the `edgeR` dispersion is very similar to the `nls`).

```r
#Uncorrected edgeR common dispersion

design <- matrix(1, ncol(assays(tmp)$counts), 1)
disps <- edgeR::estimateDisp(assays(tmp)$counts, design = design)
disps$common.dispersion
#[1] 0.6013721

#Order count means to plot predicted variance
ordered.count.means <- count.means[order(count.means)]

nbinomvar.sp = ordered.count.means* (1 + (ordered.count.means * disp.sp))
nbinomvar.nls = ordered.count.means * (1 + (ordered.count.means * disp.nls))

#Plot mean-variance scatterplots

layout(matrix(1:2, nrow = 1))
heatscatter(x = count.means,
	y = count.vars,
	log = "xy",
	xlab = "Mean (genes)",
	ylab = "Variance (genes)",
	pch = 16,
	main = "Mean-variance relationship (real data)")
abline(0,1,lty = 2)

plot(x = count.means,
	y = count.vars,
	log = "xy",
	xlab = "Mean (genes)",
	ylab = "Variance (genes)",
	pch = 16,
	cex = 0.7,
	main = "Mean-variance relationship (real data)")
abline(0,1,lty = 2)

points(x = ordered.count.means,
	y = nbinomvar.sp,
pch = 16,
col = "red",
type = "l",
lwd = 2)

points(x = ordered.count.means,
	y = nbinomvar.nls,
pch = 16,
col = "blue",
type = "l",
lwd = 2)

legend("topleft", bty = "n", lwd = 2, col = c("red", "blue"), legend = c("estimateDisp", "nls"))
```
You can see the plot here: https://imgur.com/a/JDGPF0t

So in this particular case the `nls` and the vanilla `edgeR` dispersion seem to fit the data better (going through the high mean, high variance tail) than the `splatter` estimate, most likely because of the correction.

Then I used the parameters I estimated from the data to simulate a dataset with identical characteristics, i.e. same number of genes, cells and same distribution parameters. I exclude for the moment dropouts. Nevertheless, possibly because of the sampling from a gamma distribution with shape and rate < 1 (but I may be totally wrong), it generates lots of zero-count genes.

```r
params
#Global:
#(GENES)  (CELLS)   [Seed]
#  18391     1222   352412
#
#28 additional parameters
#
#Batches:
#    [BATCHES]  [BATCH CELLS]     [Location]        [Scale]
#            1           1222            0.1            0.1
#
#Mean:
#           (RATE)            (SHAPE)
# 3.54464767812784  0.477558477636319
#
#Library size:
#       (LOCATION)            (SCALE)             (Norm)
# 8.72139258232894  0.722805887641284              FALSE
#
#Exprs outliers:
#     (PROBABILITY)          (LOCATION)             (SCALE)
#0.0112980474026771    5.41885491408814   0.932559246701361
#
#Groups:
#     [Groups]  [Group Probs]
#            1              1
#
#Diff expr:
#[Probability]    [Down Prob]     [Location]        [Scale]
#          0.1            0.5            0.1            0.4
#
#BCV:
#    (COMMON DISP)              (DOF)
#0.250343033522411   44.1812638968684
#
#Dropout:
#            [Type]          (MIDPOINT)             (SHAPE)
#              none  -0.136956636896372  -0.994259148000094
#
#Paths:
#        [From]        [Length]          [Skew]    [Non-linear]  [Sigma Factor]
#             0             100             0.5             0.1             0.8

sim <- splatSimulate( method="groups",
                          params = params,  
                          dropout.type = "none")

length(which(rowSums(counts(sim)) == 0))
#[1] 1305
```
I do again the same type of plot, and this time the cloud looks quite off, especially concerning the dispersion that was fit on the real dataset earlier. The new `nls` fit is also different, although more similar to the old one than the one in the parameters:

```r
#Look at mean-variance relationship

sim.vars <- rowVars(assays(sim)$counts)
sim.means <- rowMeans(assays(sim)$counts)

ordered.sim.means <- sim.means[order(sim.means)]

disp.sp <- metadata(sim)$Params@bcv.common

sim.est.nls <- nls(sim.vars ~ sim.means * (1 + (sim.means * x)))
sim.disp.nls <- summary(sim.est.nls)$coefficients[1]

#Check the new dispersion estimate by nls
sim.disp.nls 
#[1] 0.8646889

sim.nbinomvar.sp = ordered.sim.means * (1 + (ordered.sim.means * disp.sp))
sim.nbinomvar.nls = ordered.sim.means * (1 + (ordered.sim.means * sim.disp.nls))

heatscatter(x = sim.means,
	y = sim.vars,
	log = "xy",
	xlab = "Mean (genes)",
	ylab = "Variance (genes)",
	pch = 16,
	main = "Mean-variance relationship")
abline(0,1,lty = 2)

plot(x = sim.means,
	y = sim.vars,
	log = "xy",
	xlab = "Mean (genes)",
	ylab = "Variance (genes)",
	pch = 16,
	main = "Mean-variance relationship")
abline(0,1,lty = 2)

points(x = ordered.sim.means,
	y = sim.nbinomvar.sp,
pch = 16,
col = "red",
type = "l",
lwd = 2)

points(x = ordered.sim.means,
	y = sim.nbinomvar.nls,
pch = 16,
col = "blue",
type = "l",
lwd = 2)

points(x = ordered.count.means,
	y = nbinomvar.nls,
pch = 16,
col = "orange",
type = "l",
lwd = 2)


legend("topleft", bty = "n", lwd = 2, col = c("red", "blue", "orange"), legend = c("estimateDisp", "nls", "nls (old)"))
```

Here is the plot: https://imgur.com/a/fSIZPuT

This is where I get confused: my understanding is that I would get a distribution with a similar dispersion to the one in the parameters, but it looks like a very different one. 
Is there something I'm doing wrong, or totally missing?

Apologies for the long post!

**Comment by lazappi** [comment]
Hi @gdagstn 

Thanks for giving Splatter a go and taking the time to look at this in so much detail.

As you have probably realised from what you have done the estimation of the mean-variance relationship is part of the Splat estimation procedure that could do with some work. What we use currently is somewhat ad hoc and it is something we should look at improving. The nls method might be one approach to look at. I think your simulated dataset looks ok though, it's not too different to the real data, although it's a bit less variable.

Happy to discuss this more if you have specific questions.

(FYI images can be inserted directly into an issue which can be a bit easier to follow without opening other pages)

**Comment by gdagstn** [comment]
Hi Luke,
sorry for the external links.
Thanks for your answer and your clarifications. I understand your point and I agree with you that the simulation is perfectly good to use. 
I have no particular questions at the moment; I will be using Splatter in these days and will let you know if anything happens.

**Comment by ilia-kats** [comment]
I have a question related to this. I also observe much higher dispersions in simulated data compared to the underlying real data. As far as I understand, the underlying biological assumption is that each gene has an associated biological variation, which is captured by the negative binomial overdispersion parameter and is a decreasing function of this gene's average expression. This is also why in the splatter paper, you talk about gene-wise dispersion.
That would mean that the proper generative model would be to sample from the dispersion prior, and then scale it by the gene's expression. Expression here is the biological expression.
But how Splatter's model is set up is that the sampled dispersion is scaled by gene expression times library size. I think that this is where the additional dispersion comes from, now also the library size prior affects the NB dispersion parameter.

My question now is: Am I completely misunderstanding how this is supposed to work? If not, I would be up for a pull request to do the library size scaling in a later step.

**Comment by lazappi** [comment]
Hi @ilia-kats 

Thanks for the comment! I think this is worthy of some more discussion so I'm going to create a new issue.
