### ISSUE TITLE
simulating cancer single cell expression data with CNV events

### ISSUE THREAD

**Issue by akdess** [Oshlack/splatter#73]
Hi, 
Thanks a lot for this great tool. What is the basic way of simulating cancer single cell expression data and inserting large scale amplification/deletion events in the data? 
Thanks a lot!

**Comment by lazappi** [comment]
Hi @akdess 

Splatter simulates data at the count level so there is no concept of variants in any of the models but we can simulate different groups of cells which might be what you want. If you could describe your situation in more detail I might be able to suggest some parameters that would work.

**Comment by akdess** [comment]
Thanks a lot for the reply. Can we insert deletions or amplifications in some cells?

**Comment by lazappi** [comment]
As I said before there isn't any concept of insertions/amplifications (or any other kind of variant) in Splatter so that isn't really something you could do. You could possibly model the effects of those variants on gene expression, so have some genes more/less expressed in some cells.
