### ISSUE TITLE
splatSimDE function available?  

### ISSUE THREAD

**Issue by DanSchnell** [Oshlack/splatter#77]
Hi 
This package looks very handy, thanks. I've installed version 1.8.0 and am running R3.6.0 in RStudio.
I'm trying to create dataset(s) with differential expression, but the function splatSimDE does not seem to be available--it does appear in the Help window though.  Is there a special way to call it or a different workflow now?
Thanks,
Dan

**Comment by lazappi** [comment]
`splatSimDE` is an internal function that isn't designed to be called by a user. The normal way to use the splat simulation is via the `splatSimulate` function (or the specific method wrappers `splatSimulateGroups` and `splatSimulatePaths`). There are a few unusual cases where it can be helpful to access `splatSimDE` directly in which case you need to use `splatter:::splatSimDE()`.

**Comment by DanSchnell** [comment]
Hi Luke,
Thanks for taking a look into this...
I tried the ::: (and ::) notation and neither seemed to do it--see below.
Thoughts?
> ss=splatter:::splatSimDE(sim.groups,params1)
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'splatSimDE' not found
> ss=splatter::splatSimDE(sim.groups,params1)
Error: 'splatSimDE' is not an exported object from 'namespace:splatter'

**Comment by lazappi** [comment]
I think you probably want one of `splatSimPathDE` or `splatSimGroupDE`. I can't remember if there was a `splatSimDE` at some stage but there are two different functions now depending on what you are trying to simulate.

**Comment by lazappi** [comment]
I closing this issue but feel free to comment if you have more questions.
