### ISSUE TITLE
Specify DE genes in Splatter

### ISSUE THREAD

**Issue by louiscam** [Oshlack/splatter#79]
Hi,

I have a question related to specifying which genes are DE in Splatter, and controlling for the percentage of cells in the cell cluster of interest in which these genes are differentially expressed.

My goal is to generate a cell-by-gene expression matrix with the following characteristics:
- Cells: 2 clusters of cells, K and C (you can think of these as cell types)
- Genes: if I have say a 60 genes, I would like genes G1 to G20 to be differentially expressed between K and C, genes 21 to G40 to be partly differentially expressed (e.g. highly expressed in a random subset of K cells, you can think of these genes as markers for subpopulations of C1 cells) and genes G41 to G100 to be NOT differentially expressed between K and C

Could you please tell me whether this is doable with Splatter? Thanks for your help!

**Comment by lazappi** [comment]
I think you can something close to this using the Splat simulation but don't know if it will be exactly what you want.

> Cells: 2 clusters of cells, K and C (you can think of these as cell types)

The size and number of clusters are controlled by setting the `group.prob` parameter, for example `group.prob = c(0.5, 0.5)` would give two clusters of equal size.

> Genes: if I have say a 60 genes, I would like genes G1 to G20 to be differentially expressed between K and C, genes 21 to G40 to be partly differentially expressed (e.g. highly expressed in a random subset of K cells, you can think of these genes as markers for subpopulations of C1 cells) and genes G41 to G100 to be NOT differentially expressed between K and C

Differential expression is controlled by the `de.prob` (number of DE genes), `de.facLoc` and `de.facScale` (together the 'size' of the DE, how different the cells are) parameters. I think what you want is three populations of cells, two of which are closely related (C1 and C2) and another which is different. The Splat simulation is probabilistic so it's not (easily) possible to define exactly which genes are DE (although there are possible workarounds).

**Comment by louiscam** [comment]
Ok thank you very much for the explanation Luke!

**Comment by lazappi** [comment]
I'll close this now but feel free to open another issue if you have more questions.

**Comment by asifzubair** [comment]
Hi @lazappi , just following up on this discussion - are the differentially expressed genes chosen randomly or would it be possible to have the same genes differentially expressed across simulations. 

Essentially what I am trying to do is generate multiple single-cell data sets where I hold all the parameters constant and only change the group fractions. Would it be possible using splatter? 

Thank you.

**Comment by lazappi** [comment]
Yes, currently in the Splat simulation the genes are chosen randomly. The problem with not being able to generate multiple simulations from the with the same gene structure but different group proportions is a known problem with how Splat works. I am currently working on a new simulation that will make this much easier to do. In the meantime one work around is to generate a much larger simulation than you need and split that up into the sizes you want (hopefully that makes sense).

**Comment by asifzubair** [comment]
Thank you, @lazappi . I think I understand what you mean. Make a much larger simulation based on the total number of cells required and then split it to make separate datasets?

**Comment by lazappi** [comment]
👍 Yep. You can use the batch effect parameters as well if you want some kind of batch noise.

**Comment by asifzubair** [comment]
Great, thanks!  Also, just curious, are you planning the new simulation as an enhancement to splatter or would it be a separate package?

**Comment by lazappi** [comment]
It will be a new simulation within the Splatter package.

**Comment by asifzubair** [comment]
Hi @lazappi . I followed your advice to break up the big simulation into requisite proportions. However, I had a question about how group means are chosen. I mean if I average expression across cells for different groups (cell types), shouldn't the mean expression be reflective of how the differential expression has been decided. 
For example, let's say I simulate 4 groups and then look at the DE pattern:
```
> rowData(splat_sim)
DataFrame with 2000 rows and 8 columns
             Gene         BaseGeneMean OutlierFactor             GeneMean      DEFacGroup1      DEFacGroup2 DEFacGroup3 DEFacGroup4
         <factor>            <numeric>     <numeric>            <numeric>        <numeric>        <numeric>   <numeric>   <numeric>
Gene1       Gene1    0.161030892680062             1    0.161030892680062                1                1           1           1
Gene2       Gene2     5.17876234820587             1     5.17876234820587 1.60825216139344 1.09356051003854           1           1
Gene3       Gene3   0.0477274262185839             1   0.0477274262185839                1                1           1           1
Gene4       Gene4     4.58683162269251             1     4.58683162269251  1.5152521988326                1           1           1
Gene5       Gene5     4.45360735311527             1     4.45360735311527                1                1           1           1
...           ...                  ...           ...                  ...              ...              ...         ...         ...
Gene1996 Gene1996    0.595226773220948             1    0.595226773220948                1                1           1           1
Gene1997 Gene1997    0.463101553661644             1    0.463101553661644                1                1           1           1
Gene1998 Gene1998     0.84950601863428             1     0.84950601863428                1                1           1           1
Gene1999 Gene1999 0.000541285848648173             1 0.000541285848648173                1                1           1           1
Gene2000 Gene2000     1.31556621460685             1     1.31556621460685                1                1           1           1
```
And then look at the group means:
```
> head(splat_group_means)
          Group1     Group2     Group3     Group4
Gene1  0.7452229  0.7972222  0.8870056  0.7318182
Gene2 30.8949045 30.8472222 32.6073446 30.4606061
Gene3  0.2197452  0.2361111  0.2740113  0.2227273
Gene4 26.2866242 26.4138889 26.6073446 26.8545455
Gene5 23.7627389 23.5361111 23.0225989 23.0696970
Gene6  0.4076433  0.4027778  0.4858757  0.4060606
```
Shouldn't the group means be reflective of the way DE pattern has been decided? So, say, for example, Gene4 should have a bit higher expression in Group1 compared to other groups. But I don't see this to be the case. Could you please let me know if my reasoning is sound? Thanks!

**Comment by lazappi** [comment]
I think your intuition is correct but not sure why the numbers don't match up. Where does `splat_group_means` come from? Possibly you aren't looking in quite the right place.

**Comment by asifzubair** [comment]
Thank you for confirming my intuition, @lazappi . You were right, I don't think I was picking the cells correctly - mostly because I disregarded that cells were treated as factors in `colData()`. After, I fixed that it makes more sense:
```
> SingleCellExperiment::rowData(splat_sim)
DataFrame with 2000 rows and 8 columns
##              Gene       BaseGeneMean OutlierFactor           GeneMean
##          <factor>          <numeric>     <numeric>          <numeric>
## Gene1       Gene1   6.45135872092825             1   6.45135872092825
## Gene2       Gene2 0.0725519730783946             1 0.0725519730783946
## Gene3       Gene3   1.23885592146663             1   1.23885592146663
## Gene4       Gene4   1.17640492247369             1   1.17640492247369
## Gene5       Gene5  0.197514300980963             1  0.197514300980963
## ...           ...                ...           ...                ...
## Gene1996 Gene1996 0.0104151107656626             1 0.0104151107656626
## Gene1997 Gene1997    1.3152411681482             1    1.3152411681482
## Gene1998 Gene1998 0.0812994812003122             1 0.0812994812003122
## Gene1999 Gene1999 0.0507980124101796             1 0.0507980124101796
## Gene2000 Gene2000   0.51040193291887             1   0.51040193291887
##                DEFacGroup1      DEFacGroup2       DEFacGroup3
##                  <numeric>        <numeric>         <numeric>
## Gene1                    1                1                 1
## Gene2                    1                1                 1
## Gene3     2.16401768228179                1  1.02493724898768
## Gene4                    1                1                 1
## Gene5                    1                1                 1
## ...                    ...              ...               ...
## Gene1996 0.551172654357728                1                 1
## Gene1997                 1                1                 1
## Gene1998                 1 1.37659198310672 0.744816484362254
## Gene1999  0.52496545066184                1 0.810659980561758
## Gene2000                 1                1                 1
##                DEFacGroup4
##                  <numeric>
## Gene1                    1
## Gene2                    1
## Gene3                    1
## Gene4                    1
## Gene5                    1
## ...                    ...
## Gene1996 0.483767860595075
## Gene1997                 1
## Gene1998                 1
## Gene1999                 1
## Gene2000                 1
> head(splat_group_means)
##           Group1     Group2     Group3     Group4
## Gene1 35.3917197 47.9444444 47.9943503 46.6212121
## Gene2  0.3726115  0.4055556  0.4293785  0.4878788
## Gene3 14.5732484  8.7944444  9.5875706  8.9606061
## Gene4  6.2579618  8.2833333  9.2768362  8.8333333
## Gene5  1.0509554  1.4666667  1.4350282  1.4757576
## Gene6  0.8662420  1.3111111  1.1016949  1.2909091
``` 
Now, for example, `Gene3` shows slightly higher expression in `Group1` and `Group3` (as expected).

Thank you for your help, @lazappi ! 

PS: I got the group means by picking cells that only belonged to a particular group and then averaging the expression across cells.

**Comment by genecell** [comment]
Hi @lazappi, just following up on the above discussions, is it reasonable to select top ranked marker genes as ground truth basing on the 'DEFac' values from highest to lowest for each group? For example, set the 30 genes with the highest 'DEFacGroup1' values as the top 30 marker genes for Group 1. 

Thank you!

**Comment by lazappi** [comment]
In principle that is correct, the genes with the highest `DEFacGroup1` values should be the most up-regulated genes for Group1.

The complication is if by chance the same gene has been selected to be up-regulated in two groups. In that case, you need to compare the DE factors as described here https://github.com/Oshlack/splatter/issues/57#issuecomment-427703128. I think for your case that should be pretty rare though unless you are simulating very few genes or lots of DE genes.
