### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by xuebaliang** [Oshlack/splatter#80]
hello, recently I want to use the splatter to produce some simulation dataset about single cell. But unfortunately I meet some trouble in installation. I search this problem in the Intnet, and it seems that BiocManager can not be used recently. Therefore I want to ask you: are there another way to install the splatter package, such as from github and so on?
> BiocManager::install("splatter")
Error: Bioconductor version cannot be validated; no internet connection?

**Comment by lazappi** [comment]
To me that error message suggests that you have a problem connecting to the internet. As far as I now there has been no recent problems with BiocManager. You can install Splatter from GitHub using the following code but it is highly not recommended as it may cause other problems.

```
remotes::install_github("Oshlack/splatter") # Development version
remotes::install_github("Oshlack/splatter@RELEASE_3_9") # Current release version
```
