### ISSUE TITLE
Batch effects 

### ISSUE THREAD

**Issue by MartinLoza** [Oshlack/splatter#81]
Good day. I am wondering if I can simulate batch effect on two batches with different groups of cells. According to documentation, looks like I can only simulate batch effects on batches with the same groups of cells.

**Comment by lazappi** [comment]
Hi @MartinLoza 

I think what you want to do is simulate multiple batches with different group proportions, something like Batch 1 = 100 A + 200 B + 300 C and Batch 2 = 200 A + 300 B + 100 C?

Assuming that I have understood you properly that is something is a bit tricky to do with the current Splat simulation. The way it is set up assumes that each batch is a technical replicate with the same cell type proportions. One way around this is to simulate more cells that you need and then down sample them to get what you want, for example simulate two batches with 300 A + 300 B + 300 C and then remove some cells to get the batches above. Hopefully that make sense 😸.

(P.S. This is a known problem with how Splat works and is something I'm hoping to fix in a new simulation I'm working on)

**Comment by MartinLoza** [comment]
Hi @lazappi , I was thinking more in a simulation like this:
Batch 1 = A + B + C
Batch 2 = A + B + D
for example, where the cell types on each batch can be different
Thanks for your response and have a nice day!

**Comment by lazappi** [comment]
You should be able to do that using the approach I mentioned above. Create a simulation with two batches and four groups and then remove one of the batches from each group.

**Comment by MartinLoza** [comment]
Hi, you are right. The approach you gave me could be used to create the simulation I am looking for. Thanks for your help!
