### ISSUE TITLE
not able to estimate from scRNAseq package

### ISSUE THREAD

**Issue by asifzubair** [Oshlack/splatter#82]
I'm trying to estimate parameters from datasets available in the [scRNAseq](https://bioconductor.org/packages/3.10/data/experiment/html/scRNAseq.html) package. Since these datasets are already of type `SingleCellExperiment`, 
```r
> allen <- scRNAseq::ReprocessedAllenData()
> allen
class: SingleCellExperiment 
dim: 20816 379 
metadata(2): SuppInfo which_qc
assays(4): tophat_counts cufflinks_fpkm rsem_counts rsem_tpm
rownames(20816): 0610007P14Rik 0610009B22Rik ... Zzef1 Zzz3
rowData names(0):
colnames(379): SRR2140028 SRR2140022 ... SRR2139341 SRR2139336
colData names(22): NREADS NALIGNED ... Animal.ID passes_qc_checks_s
reducedDimNames(0):
spikeNames(0):
altExpNames(1): ERCC
```
I thought I should be able to do something like this: 
```r
> params <- splatter::splatEstimate(allen)
```
However, I get an error when I do that:
```
Error in assay(object, i = exprs_values, ...) : 
  'assay(<SingleCellExperiment>, i="character", ...)' invalid subscript 'i'
'counts' not in names(assays(<SingleCellExperiment>))
```
Any ideas on what's going on and how to fix it ? 

Thanks!

**Comment by asifzubair** [comment]
Ok, I was able to estimate params using this:
```r
> counts <- (assay(allen))
> params <- splatEstimate(counts)
<simpleError in optim(par = vstart, fn = fnobj, fix.arg = fix.arg, obs = data,     gr = gradient, pdistnam = pdistname, hessian = TRUE, method = meth,     lower = lower, upper = upper, ...): non-finite finite-difference value [2]>
```
The `counts` function doesn't seem to be working with `allen`. But, still confused that I couldn't simply use `allen` directly. 

Also, is `simpleError` something to worry about ?

**Comment by lazappi** [comment]
Hi @asifzubair 

The first error is because this dataset doesn't have anything in the `counts` slot. If you look at the assays above there is `tophat_counts`,  `cufflinks_fpkm`,  `rsem_counts` and `rsem_tpm` but no `counts`. This is fairly unusual but there should probably be a better error message (or fall back to whatever the first assay is).

The `simpleError` is from one of the fitting stages. It's probably not something to worry about but ideally you shouldn't see that message. It's something else to look in to.

**Comment by asifzubair** [comment]
Yes, it is kinda odd that the `counts` slot is missing. However, the `scRNAseq` package is from the authors of `SingleCellExperiment`, so they might have a reason for doing that. BTW, the same error is thrown when I call `counts(allen)` - because of the reason you stated.

**Comment by asifzubair** [comment]
Hi @lazappi 

Thank you for addressing this issue in the codebase. 

Also, I was wondering if you have any suggestions on how to pick appropriate `de.facLoc` and `de.facScale` values? I find that when testing my method it is sensitive to how these values are set and I don't want to set them manually. Is there some way I could *estimate* them as well? 

Thank you, 
Best, 

Asif

**Comment by lazappi** [comment]
If you have a dataset with known groups in it you can perform a differential expression analysis between two groups and fit a log-normal distribution to the foldchange (not log-foldchange) estimates. This is approximately what Splat is trying to simulate. I usually use the `fitdistrplus` package for that kind of fitting https://cran.r-project.org/web/packages/fitdistrplus/index.html.

**Comment by asifzubair** [comment]
Hi @lazappi - would you recommend fitting the log-normal to the FC between two groups or between one group and the rest? 

Also - I just wanted your thoughts on this: recently, in the [CellAssign](https://www.nature.com/articles/s41592-019-0529-1) paper they claimed that the splatter model needs to be augmented because it doesn't model logFC well in all cases. They have some very (draft) experiments to demonstrate this [here](https://github.com/Irrationone/cellassign-paper/blob/master/analysis/jupyter/modeling_differential_expression.ipynb). Do you think their claims hold water and that perhaps the augmented model should be incorporated into splatter? Thanks!

**Comment by lazappi** [comment]
The generated factors are relative to a fictional base cell so I think fitting one group compared to everything else would be closest to that. This is a very approximate process though so I'm not sure it would make too much difference. 

Thanks for letting me know about the comments in the CellAssign paper! 😸 I hadn't seen those before. I haven't looked at it in a lot of detail but it is definitely possibly that another distribution is a better fit. It's definitely something to consider adding as an option to the Splat model.
