### ISSUE TITLE
change values on Differential Expression parameters

### ISSUE THREAD

**Issue by juanangel87** [Oshlack/splatter#83]
Hello!
I am trying to simulate single-cell data, generating different populations. 
I am wondering if, and how, I can change values of the Differential expression paramters (% of differential expressed genes and the difference in expression).
In newSplatParams() We have 
Diff expr:
[Probability]    [Down Prob]     [Location]        [Scale]

But I do not know how to change them.
THank you for your help in advance!
J

**Comment by lazappi** [comment]
Hi @juanangel87 

Thanks for giving Splatter a go! As this is a question about usage can you please repost it on the Bioconductor support site https://support.bioconductor.org/ and make sure you tag Splatter.

Thanks
