### ISSUE TITLE
addQCPer* renamed to addPer*QC in scater

### ISSUE THREAD

**Issue by LTLA** [Oshlack/splatter#84]
Apologies for the last-minute renaming; I realized that all the other functions were "per-cell QC" or "per-feature QC" so I took the opportunity to standardize the names. This change is effective as of scater 1.13.27. If you do not respond before the next BioC build, I will make a request to the BioC core team to change the relevant line of code on your behalf.

**Comment by LTLA** [comment]
Thanks to @hpages, this is done. Make sure you re-sync your repository with the BioC repo.

**Comment by lazappi** [comment]
Thanks! Sorry for the slow response.
