### ISSUE TITLE
Problem installing version 1.10.0 from Bioconductor

### ISSUE THREAD

**Issue by DanSchnell** [Oshlack/splatter#86]
I've tried a couple ways of installing the newest version of splatter (1.10.0) from bioconductor and each time the version seems to be 1.8.0.  Installed from github and version is denoted 1.9.11.

How can I install 1.10, assuming the Bioconductor version is most up-to-date?

Thanks much!

Running R 3.6.1 in RStudio, BiocManager 1.3.10 and being careful to specify the installation library path so I don't think that's the isssue.

**Comment by lazappi** [comment]
Hi @DanSchnell 

It sounds like you might still be on the last Bioconductor release. You can check using `BiocManager::version()`.  The current release is 3.10. If you are on an old version you should be able to update all your packages using `BiocManager::install()`.

The version from GitHub should be the same as what is on Bioconductor. I just haven't got around to bumping the version numbers here.

**Comment by DanSchnell** [comment]
Thanks Luke!  Yes, the command you provided indicates that the Bioconductor version being called is 3.9—I’ll need to figure out how to update that.

I’ve seen some of the other posts about exercising (more) control of the gene means and am working on modifications to do so, while preserving the other sources of variability including outlier variability.

In doing so I ran into a situation wherein some of the rows were entirely 0s and this seemed to induce a problem downstream at the BCV +/- Dropout steps.  From your POV, are any theoretical assumptions or estimation particulars that would be in effect altered by dropping features with entirely 0 counts from the count matrix used in the parameter estimation call that would affect the parameter estimation and/or simulation steps?

Best,
Dan

**Comment by lazappi** [comment]
I think it's fine to remove the all zero features, that's what I usually do as there are lots of methods that will fail if you include them. Whether you do any more filtering than that depends on what kind of datasets you are interested in testing your methods on (raw or filtered).

**Comment by DanSchnell** [comment]
Thanks for the feedback Luke.

Best,
Dan

**Comment by lazappi** [comment]
No worries. Feel free to open another issue or post on the Bioconductor forums if you have any other questions.

**Comment by rpeys** [comment]
A related question -- is there a specific version of Bioconductor that we should use when installing? I am using `Bioconductor version 3.16 (BiocManager 1.30.20), R 4.2.3 (2023-03-15)` and many dependencies fail to install. Is my Bioconductor version too recent? Thanks!

```Bioconductor version 3.16 (BiocManager 1.30.20), R 4.2.3 (2023-03-15)

Installing package(s) 'BiocVersion', 'splatter'

also installing the dependencies ‘zlibbioc’, ‘formatR’, ‘sitmo’, ‘systemfonts’, ‘textshaping’, ‘bitops’, ‘XVector’, ‘lambda.r’, ‘futile.options’, ‘magrittr’, ‘pkgconfig’, ‘colorspace’, ‘sparseMatrixStats’, ‘RcppHNSW’, ‘ScaledMatrix’, ‘irlba’, ‘rsvd’, ‘beeswarm’, ‘vipor’, ‘RcppEigen’, ‘FNN’, ‘RcppAnnoy’, ‘RcppProgress’, ‘dqrng’, ‘Cairo’, ‘png’, ‘ragg’, ‘RCurl’, ‘GenomeInfoDbData’, ‘GenomicRanges’, ‘DelayedArray’, ‘futile.logger’, ‘snow’, ‘BH’, ‘cpp11’, ‘backports’, ‘limma’, ‘Rcpp’, ‘gtable’, ‘isoband’, ‘tibble’, ‘withr’, ‘farver’, ‘labeling’, ‘munsell’, ‘R6’, ‘RColorBrewer’, ‘viridisLite’, ‘scuttle’, ‘gridExtra’, ‘DelayedMatrixStats’, ‘beachmat’, ‘BiocNeighbors’, ‘BiocSingular’, ‘ggbeeswarm’, ‘viridis’, ‘Rtsne’, ‘RcppML’, ‘uwot’, ‘pheatmap’, ‘ggrastr’, ‘ggrepel’, ‘MatrixGenerics’, ‘Biobase’, ‘IRanges’, ‘GenomeInfoDb’, ‘SingleCellExperiment’, ‘BiocGenerics’, ‘BiocParallel’, ‘checkmate’, ‘edgeR’, ‘fitdistrplus’, ‘ggplot2’, ‘locfit’, ‘matrixStats’, ‘scales’, ‘scater’, ‘SummarizedExperiment’, ‘S4Vectors’


Warning message in install.packages(...):
“installation of package ‘irlba’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘Cairo’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘png’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘sitmo’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘systemfonts’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘RcppEigen’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘RCurl’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘Rtsne’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘edgeR’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘textshaping’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘dqrng’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘RcppML’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘ragg’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘uwot’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘GenomeInfoDb’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘GenomicRanges’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘BiocSingular’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘ggrastr’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘SummarizedExperiment’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘SingleCellExperiment’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘scuttle’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘scater’ had non-zero exit status”
Warning message in install.packages(...):
“installation of package ‘splatter’ had non-zero exit status”
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    boot, foreign, lattice, Matrix, spatial, survival
```
