### ISSUE TITLE
parameters in the metadata of new data didn't change after I updated the parameters

### ISSUE THREAD

**Issue by yingstat** [Oshlack/splatter#87]
Hi，
Thanks for the great tool. 
I was playing around with the tool and found the parameters in the metadata didn't change after I updated the parameters. Can you tell me why I didn't get it correct and in which way should I get the correct metadata of parameters?

1. Simulate the data without dropouts

```
params <- newSplatParams()
params <- setParams(params,
                    nGenes=2000,
                    batchCells=1000,
                    group.prob = c(0.1, 0.2, 0.2, 0.2, 0.3),
                    de.prob = c(0.2, 0.4, 0.2, 0.1, 0.1),
                    de.downProb = c(0.2, 0.3, 0.2, 0.3, 0.3),
                    de.facLoc = c(0.1, 0.1, 0.1, 0.15, 0.2),
                    de.facScale = c(0.2, 0.4, 0.2, 0.5, 0.4),
                    dropout.type = "none",
                    seed = 100)
data <- splatSimulate(params, method = "groups", verbose = FALSE)

```

2. Simulate the data with dropouts with updated parameters

```
params <- setParams(params, 
                    update = list(dropout.type = "experiment",
                                  dropout.mid = 3))
data.drop <- splatter:::splatSimDropout(data, params = params)

```

The parameters in the metadata didn't change after I update the parameters

```
data.drop@metadata$Params@dropout.mid
# 0 
data.drop@metadata$Params@dropout.type
# "none"
```

But some of the estimate parameters changes like "dropout.mid"

```
est_params <- splatEstimate(data.drop)
est_params@dropout.mid
# 2.385732
```
Still, the estimate parameter of "dropout.type" didn't change as the updated version
```
est_params@dropout.type
# "none"
```

**Comment by lazappi** [comment]
Hi @yingstat 

Thanks for giving Splatter a go. The `splatter:::splatSimDropout()` function is an internal function that isn't really meant to be used by users (although I have sometimes suggested it as a way to do particular things). The parameters are only saved at the end of the normal `splatSimulate()` function which is why they haven't been updated here. You can manually replace them using something like:

```r
metadata(data.drop, "Params") <- params
```

(I can't run code at the moment so that might not be quite right but it will be closeish)

**Comment by yingstat** [comment]
Thank you, I understand. 
```
metadata(data.drop, "Params") <- params
Error in .local(x, ..., value) : unused argument (value)
```
This works：
`metadata(data.drop)$Params <- params`

**Comment by lazappi** [comment]
Yes, that's what I meant. Thanks for posting the correct code 😸!

I think we are done with this now so I'm going to close the issue. Feel free to open another one or post on the Bioconductor forums if you have any more questions.
