### ISSUE TITLE
add dropout noise in the existing matrix (real data)

### ISSUE THREAD

**Issue by gerrardmai** [Oshlack/splatter#88]
How to add dropout in the existing matrix? not simulated matrix?

**Comment by lazappi** [comment]
Hi @gerrardmai 

I'm not sure if I understand what you are asking or if this is related to Splatter? A real dataset will already contain dropout (if it is present) so I'm not sure it makes sense to add it?

**Comment by lazappi** [comment]
I'm closing this issue now but please reopen it if you have more information.

**Comment by wanlinjuan** [comment]
Hi I think I face the same issue. I use "splatSimDropout" function to add dropout to real data matrix. Here is the error message:
Error in `assays<-`(`*tmp*`, value = `*vtmp*`) : 
  please use 'assay(x, withDimnames=FALSE)) <- value' or 'assays(x,
  withDimnames=FALSE)) <- value' when the rownames or colnames of the
  supplied assay(s) are not identical to those of the receiving
  SingleCellExperiment object 'x'
