### ISSUE TITLE
Add check for valid path.from parameter

### ISSUE THREAD

**Issue by alexisvdb** [Oshlack/splatter#91]
splatSimulate(method="paths", ... ) get stuck for some paths. There might be several causes:
1. the path contains a cycle or loop.
2. the path is not connected (there are 2 or more separate parts
3. something else?

Below is an example. The problematic path looks like this (if I understand correctly):
0 -> 1 -> 5 and a cycle from 2 -> 3 ->4 -> back to 2

```
library(splatter)
path.from <- c(0,4,2,3,1) # a problematic path; splatSimulate does not finish
sim <- splatSimulate(
  group.prob = rep(0.2,5),
  path.from = path.from,
  method = "paths")
```
 In this case, splatSimulate() does not finish and gives the following output:
```
Getting parameters...
Creating simulation object...
Simulating library sizes...
Simulating gene means...
Simulating path endpoints... # <- it seems to get stuck here.
```

Using path.from <- c(0,1,2,3,4) (a single path without a loop) finishes without problems.

I think a check can be added easily (I might be naive?) using an adjacency matrix. Taking the nth power of the adjacency matrix can be used to see where you can get from each node in n steps. This can be used to check for cycles, and probably also for checking it there are 2 or more non-connected paths.

Best regards,

Alexis Vandenbon

**Comment by lazappi** [comment]
Hi @alexisvdb 

Thanks for making this into an issue! 🎉 I didn't know about the adjacency matrix trick but that sounds like it might be a good solution, and probably more robust than what is there now. I know there are some good functions for checking these things in the **igraph** 📦 but I would like to avoid that as a dependency if I can. I will try to do this before the next Bioconductor release.
