### ISSUE TITLE
simulation differential expressed pattern

### ISSUE THREAD

**Issue by paprikachan** [Oshlack/splatter#92]
Hi, I tried to simulate two clear differential expressed patterns illustrated in [DCA paper, Figure 2](https://www.nature.com/articles/s41467-018-07931-2/figures/2).
![Screenshot 2020-02-23 at 12 14 39 AM](https://user-images.githubusercontent.com/5020011/75095592-879d9a00-55d1-11ea-859c-8799e68a5455.png)

The author declared the following methodologies.
```
Simulated scRNA-seq data

Simulated datasets were generated using the Splatter R package34. 
For the two group simulation the following parameters were used in the splatSimulate() 
R function: 
groupCells = 2, nGenes = 200, dropout.present = TRUE, dropout.shape -1, dropout.mid = 5. 
For the six group simulation the following parameters were used in the splatSimulate() 
R function: 
groupCells = 6, nGenes = 200, dropout.present = TRUE, dropout.shape -1, dropout.mid = 1.
```

While I failed to recover these two patterns, it seems the author used an old version, is it possible for me to get the similar data pattern with the current version?

**Comment by lazappi** [comment]
Hi @paprikachan 

Could you please post the code you are running and similar plots showing what the output looks like? The `sessionInfo()` output with your package versions would also be helpful.

Thanks

**Comment by lazappi** [comment]
I'm going to close this issue now but please reopen it if you have more information.

**Comment by paprikachan** [comment]
Hi @lazappi ,

As for the two group simulations, I tried with splatter_1.8.0:
```
sim <- splatSimulate(nGenes=200, batchCells=c(100, 100), seed=42, dropout.shape=-1, dropout.mid=5)
pheatmap(assays(sim)$TrueCounts, cluster_rows = F, cluster_cols = F, show_colnames = F, show_rownames = F)
```
And the heatmap looks like following:
![WeChat Screenshot_20210211174006](https://user-images.githubusercontent.com/5020011/107620773-3417d680-6c90-11eb-907c-a26f74e690d0.png)

How can I get the distinct pattern as illustrated in DCA paper, Figure 2b?

Thanks.

**Comment by lazappi** [comment]
It looks as though you haven't simulated any differential expression here. You will need to set the `group.prob` parameter and the `method = "groups"` argument otherwise you will only generate a single population. Please see `?SplatParams` and `?splatSimulate` for more details.
