### ISSUE TITLE
Dropout in path simulation

### ISSUE THREAD

**Issue by ttgump** [Oshlack/splatter#94]
It seems there is no dropout in the path simulation. Here is my code:

```
sim.paths <- splatSimulate(method = "paths")
counts     <- sim.paths@assays$data$counts
truecounts <- sim.paths@assays$data$TrueCounts
```
I compared "counts" and "truecounts", it seems they are exact same and no dropout events like the normal simulation mode. How to fix it? Thanks.

**Comment by lazappi** [comment]
Hi @ttgump 

Thanks for giving **Splatter** a go. By default dropout is turned off for the Splat simulation. To turn it on you need to set the `dropout.type` parameter. Most likely you want to set it to `experiment` unless you have a need for batch, group or cell specific dropout effects.
