### ISSUE TITLE
Forcing a different library size

### ISSUE THREAD

**Issue by dagarfield** [Oshlack/splatter#95]
Hello! 
This is less an issue as much as a call for help. :)

I'm attempting to use your package to simulate the effect of targeted sequencing -- e.g. what happens to clustering and power to detect differences between cell types if instead of focusing on the whole transcriptome, you focus on, say, 1000 specific transcripts. 

I can imagine two paths.
1) Use a standard library to estimate parameters, and then change the gene number from, e.g. 23,000 to 1,000.
2) Take an actual library, remove all but the 1000 genes. Estimate parameters, and force the library size upwards.

Do you have any thoughts about the right way to go about this? Thanks.

**Comment by lazappi** [comment]
Hi @dagarfield 

I hope **splatter** can be useful for your application.

I would probably go with the first option but you should probably try both and see how similar the generated data is. The relationship between the gene parameters (`mean.shape` and `mean.rate`) and the library size parameters (`lib.loc` and `lib.scale`) is complex and it can be hard to say what will happen without trying it.

**Comment by dagarfield** [comment]
I'll give it a go. My worry with that approach is that it loses information
about the distributions of the specific 1000 genes of interest.
But I'll give it a go and report back the results. For my reference, is
there an interpretable relationship between lib.loc and average library
size? (e.g. is that lib.loc related to an estimated mean?).

**Comment by lazappi** [comment]
The library sizes are drawn from a log-normal distribution where meanlog = `lib.loc` and sdlog = `lib.scale'. See `?rlnorm` for more details about how these relate to mean, variance etc.

**Comment by dagarfield** [comment]
An additional follow up -- what are the roles of mean.rate and mean.shape in this?  This represents something like the "true" mean (of means) from which the gene means are sampled? I wonder if, this should be set as equal in two sets of paramers if the goal is to describe strictly the effects of changes in library size on the same population of transcripts.

**Comment by lazappi** [comment]
The `mean.rate` and `mean.shape` parameters describe a Gamma distribution from which the gene means are drawn. This can be considered the "true" means and I think it makes sense to make them the same if you are interested in the library size effect. They are adjusted later based on the generated library sizes though so it depends a bit what you are most interested in.

**Comment by lazappi** [comment]
Hi @dagarfield 

I hope that has answered your question but if not please feel free to comment/reopen the issue.
