### ISSUE TITLE
Splatter parameter estimation error

### ISSUE THREAD

**Issue by aarzalluz** [Oshlack/splatter#96]
Hello,

I have been trying to use splatter to obtain parameters from my current data prior to simulation. However, I got the following error: 

`Error in nls(y ~ logistic(x, x0 = x0, k = k), data = df, start = list(x0 = 0,  : 
  step factor 0.000488281 reduced below 'minFactor' of 0.000976562`

I saw that, in a previously resolved Issue (#31), a similar error was reported, but was instead only causing a warning and the splatter `splatEstimate()` run was able to finish successfully. Hoping this was the case, I updated the package from version 1.10.0 (available through Bioconductor) to version 1.11.4 via GitHub. However, in my case the error still stops the run, and no output (or warning) is produced. Perhaps the error is not catched and the function is unable to switch to the Method of Moments method?

Here is my counts matrix as an RDS file: https://www.dropbox.com/s/adzc79mwrpw6npm/matrix.RDS?dl=0 

I hope it is useful to replicate the error. I'm using R version 3.6.3.

Thank you in advance!

Ángeles

**Comment by lazappi** [comment]
Hi @aarzalluz 

Thanks for giving Splatter a go and reporting the error! I was able to reproduce this with your matrix and Splatter v1.10.1 (the current release version). This should be being caught by the fix I described in the other issue but for some reason it doesn't seem to be. I will see if I can track down the problem and push a fix this week before the next Bioconductor release.

**Comment by lazappi** [comment]
I've pushed a commit to the devel branch to fix this. You should now get a warning about an alternative algorithm being used. I'll close the issue but please reopen it if you are still having problems.

**Comment by aarzalluz** [comment]
Hi @lazappi 

Thank you for fixing this! I'll try it out and let you know if anything else comes up.
