### ISSUE TITLE
Multiple batches and groups

### ISSUE THREAD

**Issue by annajbott** [Oshlack/splatter#99]
Hi,
Cheers, love splatter!
I'm trying to simulate a scenario with multiple batch effects and groups and sub groups.
I.e. I have an experiment with 100 patients, each belonging to one of five treatment groups. I also want to simulate multiple sequencing runs, such that there are 5 pools, each with 7 channels. 
I was thinking of making one massive count matrix and then subsetting it afterwards, and using the 5 treatment groups as the group parameter in splatter and probably the different batches as the different pools. However, I was wondering if it was possible to include multiple batch effects, so that I could have patient as another batch effect with a larger effect size than pool, and maybe channel as another batch effect with a smaller effect size.
Is this possible??
Or any ideas for how to do this?

Thanks!
Anna

**Comment by lazappi** [comment]
Hi @annajbott 

Thanks for giving Splatter a go! The way the current batch effects work is roughly equivalent to sequencing multiple samples from the same tissue. Each "batch" will have the same "groups" (usually thought of as cell types) in the same proportions. It's not really set up for the kind of nested batch effects you are describing but I have a couple of suggestions that might work. 

One approach is simulate a large dataset with batches and groups. Then to spilt this up by batch and assign each cell to a sub-batch. For each sub-batch simulate another matrix with the same dimensions but without any groups and with smaller library size parameters. This noise matrix is then added to the counts for the cell in that sub-batch (hopefully that makes sense). 

There is a script where I did something similar for a benchmarking experiment here https://github.com/theislab/scib/blob/master/notebooks/data_preprocessing/simulations/sim2.R. It might be a bit more complex than what you are looking for but hopefully it gives you some idea of the approach.

It might also be worth looking at some of the other models in Splatter such as the ZINBWaVE model which is a bit more complex to set up but lets you include arbitrary covariates for cells.

You are not alone in wanting to do things like this and it's something I'm hoping to improve if I have a chance to work on Splatter.

**Comment by lazappi** [comment]
Hi @annajbott. What that helpful or do you have have further questions. Just wondering if I can close this issue?

**Comment by annajbott** [comment]
Hi,
Yes that was helpful thanks. In the end I decided to add new batch variables to your existing code and reloaded the functions in the namespace
https://github.com/annajbott/sc_simulate/blob/master/R/splatter_simulate_channel_patients.R

Cheers!
Anna
